tenants:
  - name: es
    schema_name: es
    state_code: ES
    edware_db_username: "{{ edware_db_test_air_username }}"
    edware_db_password: "{{ edware_db_test_air_password }}"
    edware_db_host: "{{ hostvars | srl_hostvars_lookup((groups.get('reporting-db-pgpool', []) | intersect(locals) | first))['ec2_tag_Name'] }}.{{ domain }}"
    edware_db_port: 9999
  - name: ta
    schema_name: ta
    state_code: TA
    edware_db_username: "{{ edware_db_test_air_username }}"
    edware_db_password: "{{ edware_db_test_air_password }}"
    edware_db_host: "{{ hostvars | srl_hostvars_lookup((groups.get('reporting-db-pgpool', []) | intersect(locals) | first))['ec2_tag_Name'] }}.{{ domain }}"
    edware_db_port: 9999
  - name: ot
    schema_name: ot
    state_code: OT
    edware_db_username: "{{ edware_db_test_air_username }}"
    edware_db_password: "{{ edware_db_test_air_password }}"
    edware_db_host: "{{ hostvars | srl_hostvars_lookup((groups.get('reporting-db-pgpool', []) | intersect(locals) | first))['ec2_tag_Name'] }}.{{ domain }}"
    edware_db_port: 9999

migrate_tenants:
  - name: es
    schema_name: es
    migrate_dest_db_host: "{{ hostvars | srl_hostvars_lookup((groups.get('db-master', []) | intersect(locals) | first))['ec2_tag_Name'] }}.{{ domain }}"
    migrate_dest_db_username: "{{ migrate_dest_db_test_air_username }}"
    migrate_dest_db_password: "{{ migrate_dest_db_test_air_password }}"
    migrate_source_db_host: "{{ hostvars | srl_hostvars_lookup((groups.get('migrate-db', []) | intersect(locals) | first))['ec2_tag_Name'] }}.{{ domain }}"
    migrate_source_db_username: "{{ migrate_source_db_test_air_username }}"
    migrate_source_db_password: "{{ migrate_source_db_test_air_password }}"
  - name: ta
    schema_name: ta
    migrate_dest_db_host: "{{ hostvars | srl_hostvars_lookup((groups.get('db-master', []) | intersect(locals) | first))['ec2_tag_Name'] }}.{{ domain }}"
    migrate_dest_db_username: "{{ migrate_dest_db_test_air_username }}"
    migrate_dest_db_password: "{{ migrate_dest_db_test_air_password }}"
    migrate_source_db_host: "{{ hostvars | srl_hostvars_lookup((groups.get('migrate-db', []) | intersect(locals) | first))['ec2_tag_Name'] }}.{{ domain }}"
    migrate_source_db_username: "{{ migrate_source_db_test_air_username }}"
    migrate_source_db_password: "{{ migrate_source_db_test_air_password }}"
  - name: ot
    schema_name: ot
    migrate_dest_db_host: "{{ hostvars | srl_hostvars_lookup((groups.get('db-master', []) | intersect(locals) | first))['ec2_tag_Name'] }}.{{ domain }}"
    migrate_dest_db_username: "{{ migrate_dest_db_test_air_username }}"
    migrate_dest_db_password: "{{ migrate_dest_db_test_air_password }}"
    migrate_source_db_host: "{{ hostvars | srl_hostvars_lookup((groups.get('migrate-db', []) | intersect(locals) | first))['ec2_tag_Name'] }}.{{ domain }}"
    migrate_source_db_username: "{{ migrate_source_db_test_air_username }}"
    migrate_source_db_password: "{{ migrate_source_db_test_air_password }}"

staging_tenants:
  - name: es
    staging_db_username: "{{ staging_db_test_air_username }}"
    staging_db_password: "{{ staging_db_test_air_password }}"
    staging_db_host: "{{ hostvars | srl_hostvars_lookup((groups.get('migrate-db', []) | intersect(locals) | first))['ec2_tag_Name'] }}.{{ domain }}"
  - name: ta
    staging_db_username: "{{ staging_db_test_air_username }}"
    staging_db_password: "{{ staging_db_test_air_password }}"
    staging_db_host: "{{ hostvars | srl_hostvars_lookup((groups.get('migrate-db', []) | intersect(locals) | first))['ec2_tag_Name'] }}.{{ domain }}"
  - name: ot
    staging_db_username: "{{ staging_db_test_air_username }}"
    staging_db_password: "{{ staging_db_test_air_password }}"
    staging_db_host: "{{ hostvars | srl_hostvars_lookup((groups.get('migrate-db', []) | intersect(locals) | first))['ec2_tag_Name'] }}.{{ domain }}"

extract_tenants:
  - name: es
    schema_name: es
    state_code: ES
    edware_db_username: "{{ edware_extract_db_test_air_username }}"
    edware_db_password: "{{ edware_extract_db_test_air_password }}"
    edware_db_host: "{{ hostvars | srl_hostvars_lookup((groups.get('extracts-db-pgpool', []) | intersect(locals) | first))['ec2_tag_Name'] }}.{{ domain }}"
    edware_db_port: 9999
  - name: ta
    schema_name: ta
    state_code: TA
    edware_db_username: "{{ edware_extract_db_test_air_username }}"
    edware_db_password: "{{ edware_extract_db_test_air_password }}"
    edware_db_host: "{{ hostvars | srl_hostvars_lookup((groups.get('extracts-db-pgpool', []) | intersect(locals) | first))['ec2_tag_Name'] }}.{{ domain }}"
    edware_db_port: 9999
  - name: ot
    schema_name: ot
    state_code: OT
    edware_db_username: "{{ edware_extract_db_test_air_username }}"
    edware_db_password: "{{ edware_extract_db_test_air_password }}"
    edware_db_host: "{{ hostvars | srl_hostvars_lookup((groups.get('extracts-db-pgpool', []) | intersect(locals) | first))['ec2_tag_Name'] }}.{{ domain }}"
    edware_db_port: 9999