tenants:
  - name: mt
    schema_name: mt
    state_code: MT
    edware_db_username: "{{ edware_db_test_air_username }}"
    edware_db_password: "{{ edware_db_test_air_password }}"
    edware_db_host: "{{ hostvars | srl_hostvars_lookup((groups.get('reporting-db-pgpool', []) | intersect(locals) | first))['ec2_tag_Name'] }}.{{ domain }}"
    edware_db_port: 9999
  - name: nd
    schema_name: nd
    state_code: ND
    edware_db_username: "{{ edware_db_test_air_username }}"
    edware_db_password: "{{ edware_db_test_air_password }}"
    edware_db_host: "{{ hostvars | srl_hostvars_lookup((groups.get('reporting-db-pgpool', []) | intersect(locals) | first))['ec2_tag_Name'] }}.{{ domain }}"
    edware_db_port: 9999
  - name: mi
    schema_name: mi
    state_code: MI
    edware_db_username: "{{ edware_db_test_air_username }}"
    edware_db_password: "{{ edware_db_test_air_password }}"
    edware_db_host: "{{ hostvars | srl_hostvars_lookup((groups.get('reporting-db-pgpool', []) | intersect(locals) | first))['ec2_tag_Name'] }}.{{ domain }}"
    edware_db_port: 9999
  - name: nv
    schema_name: nv
    state_code: NV
    edware_db_username: "{{ edware_db_test_air_username }}"
    edware_db_password: "{{ edware_db_test_air_password }}"
    edware_db_host: "{{ hostvars | srl_hostvars_lookup((groups.get('reporting-db-pgpool', []) | intersect(locals) | first))['ec2_tag_Name'] }}.{{ domain }}"
    edware_db_port: 9999
  - name: ca
    schema_name: ca
    state_code: CA
    edware_db_username: "{{ edware_db_test_air_username }}"
    edware_db_password: "{{ edware_db_test_air_password }}"
    edware_db_host: "{{ hostvars | srl_hostvars_lookup((groups.get('reporting-db-pgpool', []) | intersect(locals) | first))['ec2_tag_Name'] }}.{{ domain }}"
    edware_db_port: 9999
  - name: fl
    schema_name: nc
    state_code: FL
    edware_db_username: "{{ edware_db_test_air_username }}"
    edware_db_password: "{{ edware_db_test_air_password }}"
    edware_db_host: "{{ hostvars | srl_hostvars_lookup((groups.get('reporting-db-pgpool', []) | intersect(locals) | first))['ec2_tag_Name'] }}.{{ domain }}"
    edware_db_port: 9999
  - name: tx
    schema_name: es
    state_code: TX
    edware_db_username: "{{ edware_db_test_air_username }}"
    edware_db_password: "{{ edware_db_test_air_password }}"
    edware_db_host: "{{ hostvars | srl_hostvars_lookup((groups.get('reporting-db-pgpool', []) | intersect(locals) | first))['ec2_tag_Name'] }}.{{ domain }}"
    edware_db_port: 9999

migrate_tenants:
  - name: mt
    schema_name: mt
    migrate_dest_db_host: "{{ hostvars | srl_hostvars_lookup((groups.get('db-master', []) | intersect(locals) | first))['ec2_tag_Name'] }}.{{ domain }}"
    migrate_dest_db_username: "{{ migrate_dest_db_test_air_username }}"
    migrate_dest_db_password: "{{ migrate_dest_db_test_air_password }}"
    migrate_source_db_host: "{{ hostvars | srl_hostvars_lookup((groups.get('migrate-db', []) | intersect(locals) | first))['ec2_tag_Name'] }}.{{ domain }}"
    migrate_source_db_username: "{{ migrate_source_db_test_air_username }}"
    migrate_source_db_password: "{{ migrate_source_db_test_air_password }}"
  - name: nd
    schema_name: nd
    migrate_dest_db_host: "{{ hostvars | srl_hostvars_lookup((groups.get('db-master', []) | intersect(locals) | first))['ec2_tag_Name'] }}.{{ domain }}"
    migrate_dest_db_username: "{{ migrate_dest_db_test_air_username }}"
    migrate_dest_db_password: "{{ migrate_dest_db_test_air_password }}"
    migrate_source_db_host: "{{ hostvars | srl_hostvars_lookup((groups.get('migrate-db', []) | intersect(locals) | first))['ec2_tag_Name'] }}.{{ domain }}"
    migrate_source_db_username: "{{ migrate_source_db_test_air_username }}"
    migrate_source_db_password: "{{ migrate_source_db_test_air_password }}"
  - name: nv
    schema_name: nv
    migrate_dest_db_host: "{{ hostvars | srl_hostvars_lookup((groups.get('db-master', []) | intersect(locals) | first))['ec2_tag_Name'] }}.{{ domain }}"
    migrate_dest_db_username: "{{ migrate_dest_db_test_air_username }}"
    migrate_dest_db_password: "{{ migrate_dest_db_test_air_password }}"
    migrate_source_db_host: "{{ hostvars | srl_hostvars_lookup((groups.get('migrate-db', []) | intersect(locals) | first))['ec2_tag_Name'] }}.{{ domain }}"
    migrate_source_db_username: "{{ migrate_source_db_test_air_username }}"
    migrate_source_db_password: "{{ migrate_source_db_test_air_password }}"
  - name: ca
    schema_name: ca
    migrate_dest_db_host: "{{ hostvars | srl_hostvars_lookup((groups.get('db-master', []) | intersect(locals) | first))['ec2_tag_Name'] }}.{{ domain }}"
    migrate_dest_db_username: "{{ migrate_dest_db_test_air_username }}"
    migrate_dest_db_password: "{{ migrate_dest_db_test_air_password }}"
    migrate_source_db_host: "{{ hostvars | srl_hostvars_lookup((groups.get('migrate-db', []) | intersect(locals) | first))['ec2_tag_Name'] }}.{{ domain }}"
    migrate_source_db_username: "{{ migrate_source_db_test_air_username }}"
    migrate_source_db_password: "{{ migrate_source_db_test_air_password }}"
  - name: tx
    schema_name: tx
    migrate_dest_db_host: "{{ hostvars | srl_hostvars_lookup((groups.get('db-master', []) | intersect(locals) | first))['ec2_tag_Name'] }}.{{ domain }}"
    migrate_dest_db_username: "{{ migrate_dest_db_test_air_username }}"
    migrate_dest_db_password: "{{ migrate_dest_db_test_air_password }}"
    migrate_source_db_host: "{{ hostvars | srl_hostvars_lookup((groups.get('migrate-db', []) | intersect(locals) | first))['ec2_tag_Name'] }}.{{ domain }}"
    migrate_source_db_username: "{{ migrate_source_db_test_air_username }}"
    migrate_source_db_password: "{{ migrate_source_db_test_air_password }}"

staging_tenants:
  - name: mt
    staging_db_username: "{{ staging_db_test_air_username }}"
    staging_db_password: "{{ staging_db_test_air_password }}"
    staging_db_host: "{{ hostvars | srl_hostvars_lookup((groups.get('migrate-db', []) | intersect(locals) | first))['ec2_tag_Name'] }}.{{ domain }}"
  - name: nd
    staging_db_username: "{{ staging_db_test_air_username }}"
    staging_db_password: "{{ staging_db_test_air_password }}"
    staging_db_host: "{{ hostvars | srl_hostvars_lookup((groups.get('migrate-db', []) | intersect(locals) | first))['ec2_tag_Name'] }}.{{ domain }}"
  - name: nv
    staging_db_username: "{{ staging_db_test_air_username }}"
    staging_db_password: "{{ staging_db_test_air_password }}"
    staging_db_host: "{{ hostvars | srl_hostvars_lookup((groups.get('migrate-db', []) | intersect(locals) | first))['ec2_tag_Name'] }}.{{ domain }}"
  - name: ca
    staging_db_username: "{{ staging_db_test_air_username }}"
    staging_db_password: "{{ staging_db_test_air_password }}"
    staging_db_host: "{{ hostvars | srl_hostvars_lookup((groups.get('migrate-db', []) | intersect(locals) | first))['ec2_tag_Name'] }}.{{ domain }}"
  - name: tx
    staging_db_username: "{{ staging_db_test_air_username }}"
    staging_db_password: "{{ staging_db_test_air_password }}"
    staging_db_host: "{{ hostvars | srl_hostvars_lookup((groups.get('migrate-db', []) | intersect(locals) | first))['ec2_tag_Name'] }}.{{ domain }}"

public_tenants:
  - name: tx
    schema_name: public_tx
    state_code: TX
    edware_db_username: "{{ edware_db_test_air_username }}"
    edware_db_password: "{{ edware_db_test_air_password }}"
    edware_db_host: "{{ hostvars | srl_hostvars_lookup((groups.get('db-public', []) | intersect(locals) | first))['ec2_tag_Name'] }}.{{ domain }}"
    edware_db_port: 5432

extract_tenants:
  - name: mt
    schema_name: mt
    state_code: MT
    edware_db_username: "{{ edware_extract_db_test_air_username }}"
    edware_db_password: "{{ edware_extract_db_test_air_password }}"
    edware_db_host: "{{ hostvars | srl_hostvars_lookup((groups.get('extracts-db-pgpool', []) | intersect(locals) | first))['ec2_tag_Name'] }}.{{ domain }}"
    edware_db_port: 9999
  - name: nd
    schema_name: nd
    state_code: ND
    edware_db_username: "{{ edware_extract_db_test_air_username }}"
    edware_db_password: "{{ edware_extract_db_test_air_password }}"
    edware_db_host: "{{ hostvars | srl_hostvars_lookup((groups.get('extracts-db-pgpool', []) | intersect(locals) | first))['ec2_tag_Name'] }}.{{ domain }}"
    edware_db_port: 9999
  - name: mi
    schema_name: mi
    state_code: MI
    edware_db_username: "{{ edware_extract_db_test_air_username }}"
    edware_db_password: "{{ edware_extract_db_test_air_password }}"
    edware_db_host: "{{ hostvars | srl_hostvars_lookup((groups.get('extracts-db-pgpool', []) | intersect(locals) | first))['ec2_tag_Name'] }}.{{ domain }}"
    edware_db_port: 9999
  - name: nv
    schema_name: nv
    state_code: NV
    edware_db_username: "{{ edware_extract_db_test_air_username }}"
    edware_db_password: "{{ edware_extract_db_test_air_password }}"
    edware_db_host: "{{ hostvars | srl_hostvars_lookup((groups.get('extracts-db-pgpool', []) | intersect(locals) | first))['ec2_tag_Name'] }}.{{ domain }}"
    edware_db_port: 9999
  - name: ca
    schema_name: ca
    state_code: CA
    edware_db_username: "{{ edware_extract_db_test_air_username }}"
    edware_db_password: "{{ edware_extract_db_test_air_password }}"
    edware_db_host: "{{ hostvars | srl_hostvars_lookup((groups.get('extracts-db-pgpool', []) | intersect(locals) | first))['ec2_tag_Name'] }}.{{ domain }}"
    edware_db_port: 9999
  - name: fl
    schema_name: nc
    state_code: FL
    edware_db_username: "{{ edware_extract_db_test_air_username }}"
    edware_db_password: "{{ edware_extract_db_test_air_password }}"
    edware_db_host: "{{ hostvars | srl_hostvars_lookup((groups.get('extracts-db-pgpool', []) | intersect(locals) | first))['ec2_tag_Name'] }}.{{ domain }}"
    edware_db_port: 9999
  - name: tx
    schema_name: es
    state_code: TX
    edware_db_username: "{{ edware_extract_db_test_air_username }}"
    edware_db_password: "{{ edware_extract_db_test_air_password }}"
    edware_db_host: "{{ hostvars | srl_hostvars_lookup((groups.get('extracts-db-pgpool', []) | intersect(locals) | first))['ec2_tag_Name'] }}.{{ domain }}"
    edware_db_port: 9999