---
- name: Configure file-trigger
  template: src=roles/edware/templates/smarter.ini.j2 dest=/opt/edware/conf/smarter.ini
  notify: restart edudl2-trigger

- name: Configure file-trigger udl
  template: src=roles/edware/templates/udl2_conf.ini.j2 dest=/opt/edware/conf/udl2_conf.ini
  notify: restart edudl2-trigger
