---
- name: Configure file-trigger
  template: src=smarter.ini.j2 dest=/opt/edware/conf/smarter.ini
  notify: restart edudl2-trigger

- name: Configure file-trigger udl
  template: src=udl_conf.ini.j2 dest=/opt/edware/conf/udl_conf.ini
  notify: restart edudl2-trigger
