#!/bin/bash

ANSIBLE_DIR=$SBAC_DEVOPS/ansible
OSUP_TOOLS=$SBAC_DEVOPS/tools/os-upgrades

PLAYBOOK=$ANSIBLE_DIR/stop-all-services.yml

rm -f $PLAYBOOK

echo "# This playbook is generated by srl-devops/tools/os-upgrade/make-stop-all-services-playbook.sh" >> $PLAYBOOK
echo "# Modifications should be made there! " >> $PLAYBOOK

for APP in $(cat $ANSIBLE_DIR/roles/orchestration/files/shutdown-sequence.txt | fgrep -v '#'); do
    sed $OSUP_TOOLS/stop-all-services.yml.template -e "s/APPNAME/$APP/g" >> $PLAYBOOK
done
