#!/bin/bash

ANSIBLE_DIR=$SBAC_DEVOPS/ansible
OSUP_TOOLS=$SBAC_DEVOPS/tools/os-upgrades

PLAYBOOK=$ANSIBLE_DIR/start-all-services.yml

rm -f $PLAYBOOK

echo "# This playbook is generated by srl-devops/tools/os-upgrade/make-start-all-services-playbook.sh" >> $PLAYBOOK
echo "# Modifications should be made there! " >> $PLAYBOOK

# NOTE: tac is a line-by-line reversing 'cat'
for APP in $(tac $ANSIBLE_DIR/roles/orchestration/files/shutdown-sequence.txt | fgrep -v '#'); do
    sed $OSUP_TOOLS/start-all-services.yml.template -e "s/APPNAME/$APP/g" >> $PLAYBOOK
done
