---

# Based on http://sensuapp.org/docs/latest/rabbitmq

- name: Require sensu_rabbit_password
  fail:
    msg: "You must provide the 'sensu_rabbit_password' variable in the group_vars/$ENV/secrets.yml file"
  when: sensu_rabbit_password is not defined

- name: Check for sensu vhost
  shell: "rabbitmqctl -q list_vhosts | grep -q /sensu"
  register: sensu_rabbit_vhost_detected
  changed_when: false
  failed_when: false

- name: Create sensu vhost
  shell: "rabbitmqctl add_vhost /sensu"
  when: sensu_rabbit_vhost_detected | failed

- name: Check for sensu user
  shell: "rabbitmqctl -q list_users | grep -q sensu"
  register: sensu_rabbit_user_detected
  changed_when: false
  failed_when: false

- name: Create sensu user
  shell: "rabbitmqctl add_user sensu '{{ sensu_rabbit_password }}'"
  when: sensu_rabbit_user_detected | failed

- name: Set sensu user perms
  shell: "rabbitmqctl set_permissions -p /sensu sensu '.*' '.*' '.*' "
  when: sensu_rabbit_user_detected | failed
