---
  - name: configure repmgr.conf
    template: src=roles/db-master/templates/repmgr.conf.j2 dest=/var/lib/pgsql/repmgr.conf

  - name: create repmgr user
    postgresql_user: name=repmgr password={{ edware_db_repmgr_password }} role_attr_flags=SUPERUSER,LOGIN

  - name: copy pg_hba.conf
    copy: src=roles/db-master/files/pg_hba.conf dest=/var/lib/pgsql/9.2/data/pg_hba.conf owner=postgres group=root mode=0600
    notify: restart postgres