---
- name: Install postgresql92-contrib
  yum: name=postgresql92-contrib state=latest

- name: Install psycopg2 on the ansible machine
  yum: state=present name=python-psycopg2

- name: configure repmgr.conf
  template: src=roles/db-master/templates/repmgr.conf.j2 dest=/var/lib/pgsql/repmgr.conf

- name: create repmgr user
  postgresql_user: login_host=localhost name=repmgr password={{ edware_db_repmgr_password }} role_attr_flags=SUPERUSER,LOGIN

- name: copy pg_hba.conf
  copy: src=roles/db-master/files/pg_hba.conf dest=/var/lib/pgsql/9.2/data/pg_hba.conf owner=postgres group=root mode=0600
  notify: restart postgres

- name: delete existing repmgr record
  shell: su - postgres -c "psql -d edware -c 'drop schema repmgr_edware_pg_cluster cascade'"


- name: place repmgr password
  copy: content="*:5432:*:repmgr:{{ edware_db_repmgr_password }}" dest=/var/lib/pgsql/.pgpass owner=postgres group=postgres mode=0600

- name: register master
  shell: su - postgres -c "PATH=$PATH:/usr/pgsql-9.2/bin repmgr --force -f /var/lib/pgsql/repmgr.conf master register"
