
---

- name: Install the application RPM
  yum:
    name: "{{ edware_rpm_name }}"
    state: latest
  tags:
    - slow

- name: Templatize smarter.ini
  template: 
    dest: /opt/edware/conf/smarter.ini
    backup: yes
    src: smarter.ini.j2
  register: smarter_ini
