---

- name: Install the latest smarter application
  yum:
    name: smarter
    state: latest
  tags:
    - slow
  notify: restart_httpd # TODO - verify this is safe to include even if there is no such handler (workers)

- name: Templatize smarter.ini
  template: 
    dest: /opt/edware/conf/smarter.ini
    backup: yes
    src: smarter.ini.j2
  register: smarter_ini
