---
- name: Configure udl 
  template: src=roles/edware/templates/udl2_conf.ini.j2 dest=/opt/edware/conf/udl2_conf.ini
  notify: restart celeryd-udl2 

- name: create gpg directory
  file: 
    path: /dev/shm/celery/gpg 
    state: directory 
    owner: udl2
    group: udl2
    mode: 0700

- name: create celery directory
  file: 
    path: /dev/shm/celery 
    state: directory 
    owner: udl2
    group: udl2
    mode: 0700

- name: create gpg directory
  file: 
    path: /opt/edware/gnupg 
    state: directory 
    owner: udl2
    group: udl2
    mode: 0700

- name: move private key to celery directory
  copy: src=roles/udl/files/sbac_smarterbalanced_org.key dest=/dev/shm/celery/sbac_smarterbalanced_org.key owner=udl2 group=udl2 mode=0600

- name: move public key to celery directory
  copy: src=roles/udl/files/sbac_smarterbalanced_org.pub dest=/dev/shm/celery/sbac_smarterbalanced_org.pub owner=udl2 group=udl2 mode=0600

- name: decrypt private key
  shell: openssl aes-256-cbc -salt -a -d -in /dev/shm/celery/sbac_smarterbalanced_org.key -out /dev/shm/celery/d_sbac_smarterbalanced_org.key -k {{ gpg_openssl_key }}

- name: import private key
  shell: 'su - udl2 -c "gpg --homedir /opt/edware/gnupg --allow-secret-key-import --import /dev/shm/celery/d_sbac_smarterbalanced_org.key"'

- name: import public key
  shell: 'su - udl2 -c "gpg --homedir /opt/edware/gnupg --import /dev/shm/celery/sbac_smarterbalanced_org.pub"'

- name: delete private key
  shell: "rm -f /dev/shm/celery/d_sbac_smarterbalanced_org.key && rm -f /dev/shm/celery/sbac_smarterbalanced_org.key"
