---
- name: Configure udl 
  template: src=roles/edware/templates/udl2_conf.ini.j2 dest=/opt/edware/conf/udl2_conf.ini
  notify: restart celeryd-udl2 

- name: create udl gpg directory
  file: path=/dev/shm/udl/gpg state=directory owner=udl2 group=udl2 mode=0700

- name: move private key to celery directory
  copy: src=roles/udl/files/sbac_smarterbalanced_org.key dest=/dev/shm/celery/sbac_smarterbalanced_org.key

- name: move public key to celery directory
  copy: src=roles/udl/files/sbac_smarterbalanced_org.pub dest=/dev/shm/celery/sbac_smarterbalanced_org.pub

- name: import private key
  shell: "gpg --homedir /dev/shm/udl/gpg --allow-secret-key-import --import /dev/shm/celery/sbac_smarterbalanced_org.key"

- name: import public key
  shell: "gpg --homedir /dev/shm/celery/gpg --import /dev/shm/celery/sbac_smarterbalanced_org.pub"

- name: delete private key
  shell: "rm roles/udl/files/sbac_smarterbalanced_org.key && rm /dev/shm/celery/sbac_smarterbalanced_org.key"