---
- name: Ensure udl2 group exists
  group:
    name: udl2
    state: present
    gid: 501

- name: Ensure udl2 user exists
  user:
    name: udl2
    state: present
    group: udl2
    uid: 501 # Specified, because it is also specified in the edudl2 RPM

