---
# Note: the smarter.ini retemaplte happens in  edware/tasks/main
# Here, we're just watching to see if it changes, and if so, restart apache.
# Normally we'd put a handler in edware, but edware role is used by several apps, 
# most of which don't have httpd.
- name: Restart apache if smarter.ini changed
  service:
    name: httpd
    state: restarted
  when: smarter_ini.changed # This is a task reference registered by the edware role

# TODO: this file is sensitive?
- name: Configure IDP sso
  copy: src=files/{{ ec2_tag_environment }}/idp_metadata.xml dest=/opt/edware/conf/idp_metadata.xml
  notify: restart httpd 


- name: Add Slash Rewrite
  template: src=rewrite-slash.conf dest=/etc/httpd/conf.d/rewrite-slash.conf
  notify: restart httpd

- name: Rewrite http to https
  template: src=rewrite-http.conf dest=/etc/httpd/conf.d/rewrite-http.conf
  notify: restart httpd

- name: Install MPM config
  copy: src=edware_worker_mpm.conf dest=/etc/httpd/conf.d/edware_worker_mpm.conf
  notify: restart httpd

  
# TODO: conside moving the 'smarter' install to edware
- name: Install the latest smarter application
  yum: name=smarter state=latest
  notify: restart httpd

