---
- include: resolv-conf.yml
  when: "{{ 'bind' not in group_names and 'nat' not in group_names and 'lz' not in group_names }}"
- include: resolv-conf-public.yml
  when: "{{ 'nat' in group_names or 'lz' in group_names }}"
- include: dns-client.yml
  when: "{{ 'bind' not in group_names }}"
- include: set-s3-yum-repos.yml

- include: patch-glibc.yml
  tags: 
    - patches
    - slow

- include: logging.yml
# Make sure service-users is before sudoers, or it can potentially remove ansible's sudo!
- include: service-users.yml  
- include: sudoers.yml
- include: nessus.yml
- include: sssd.yml 
- include: resize-root.yml
- include: disable-ad-auth.yml
  when: "{{ec2_tag_environment == 'prod'}}"
- include: ntp.yml
  when: "{{ 'bind' not in group_names }}"

- include: ../../../roles/aws-cli/tasks/main.yml

