---
- include: dns-client.yml
  when: "{{ 'bind' not in group_names }}"
- include: set-s3-yum-repos.yml

- include: patch-glibc.yml
  tags: 
    - patches
    - slow

- include: logging.yml
- include: sudoers.yml
- include: nessus.yml
- include: sssd.yml 
- include: resize-root.yml
- include: service-users.yml
- include: disable-ad-auth.yml
  when: "{{ec2_tag_environment == 'prod'}}"
- include: ntp.yml
  when: "{{ 'bind' not in group_names }}"

- include: ../../../roles/aws-cli/tasks/main.yml

