---
- include: patch-glibc.yml
- include: logging.yml
- include: dns-client.yml
  when: "{{ 'bind' not in group_names }}"
- include: nessus.yml
- include: prod-sssd.yml 
- include: resize-root.yml
- include: set-s3-yum-repos.yml
