---
# Setup nessus user on machine

- name: Create nessus user
  user:
    name: nessus
    state: present

- name: Copy in public ssh key
  authorized_key:
    state: present
    key: "{{ lookup('file', '../credentials/nessus.pub') }}"
    user: nessus

- name: Grant sudo to nessus
  lineinfile:
    dest: /etc/sudoers.d/user_nessus
    line: "nessus     ALL=(ALL) NOPASSWD: ALL"
    state: present
    create: yes
    mode: 0440

