---
# Setup nessus user on machine

- name: Create nessus user
  user:
    name: nessus
    state: present

- name: Copy in public ssh key
  authorized_key:
    state: present
    key: "{{ lookup('file', '../credentials/nessus.pub') }}"
    user: nessus

- name: Grant sudo to nessus
  # TODO: surely there is a sudo module in galaxy
  lineinfile:
    dest: /etc/sudoers
    state: present
    line: "nessus     ALL=(ALL) NOPASSWD: ALL"
