---
# Setup nessus user on machine

- name: Create nessus user
  user:
    name: nessus
    state: present

# SSH key placed in common/ssh-keys

- name: Grant sudo to nessus
  lineinfile:
    dest: /etc/sudoers.d/user_nessus
    line: "nessus     ALL=(ALL) NOPASSWD: ALL"
    state: present
    create: yes
    mode: 0440

