---
- name: Resize root paritiion
  shell: resize2fs `df|grep -e "/$"|cut -d ' ' -f1`

- name: Add resize to rc.local
  lineinfile:
    dest: /etc/rc.local
    state: present
    line: "resize2fs /dev/xvde1"
