---
# Setup resolv.conf on machine

# This task handles running instances.
- name: Setup resolv.conf to point at local bind server
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf

- name: refresh resolv.conf
  sudo: yes
  shell: "/etc/dhcp/dhclient-enter-hooks"
