---
- name: Update sssd.conf
  lineinfile: 
    dest: /etc/sssd/sssd.conf 
    regexp: '^ldap_uri = ldaps://(.*)$' 
    line: "ldap_uri = {{ ldap_urls | join(', ') }} "
    backrefs: yes
  notify: restart sssd
