---
- name: Grant sudo to ansible
  lineinfile:
    dest: /etc/sudoers.d/user_ansible
    line: 'ansible ALL=NOPASSWD: ALL'
    state: present
    create: yes
    mode: 0440

- name: Reset /etc/sudoers
  copy:
    src:  sudoers
    dest: /etc/sudoers
    mode: 0440

# TODO: Eventually have an LDAP group for prod staff

- name: Grant sudo to staff in non-Prod
  lineinfile:
    dest: /etc/sudoers.d/group_staff
    line: '%staff ALL=(ALL) ALL'
    state: present
    create: yes
    mode: 0440
  when: "{{ not ec2_tag_environment == 'prod' }}"

# TODO: Want to have clean AMIs that do not have sudo already granted to %staff
- name: Revoke sudo from staff in Prod
  file:
    path: /etc/sudoers.d/group_staff
    state: absent
  when: "{{ ec2_tag_environment == 'prod' }}"




  

