- name: Install RabbitMQ
  yum:
    state: present
    name: rabbitmq-server-3.4.4-1
    
- name: Update RabbitMQ config file
  replace: 
    dest: /etc/rabbitmq/rabbitmq.config
    regexp: '(\{ssl_listeners, \[5671\]\},)$' 
    replace: '\1        {ssl_allow_poodle_attack, true},'

- name: Restart RabbitMQ 3.4.4
  command: sudo service rabbitmq-server restart
