
- name: Copy RabbitMQ 3.4.4 RPM to rabbit server
  copy: src=../../../files/rpms/rabbitmq-server-3.4.4-1.noarch.rpm dest=./rabbitmq-server-3.4.4-1.noarch.rpm owner=ansible group=ansible mode=644

- name: Install RabbitMQ 3.4.4 RPM
  command: sudo rpm --upgrade rabbitmq-server-3.4.4-1.noarch.rpm

- name: Restart RabbitMQ 3.4.4
  command: sudo service rabbitmq-server restart
