---
- name: Stop PgPool
  service: name=pgpool state=stopped enabled=yes

- name: Template pgpool.conf
  template: src=roles/db-pgpool/templates/pgpool.conf.j2 dest="/etc/pgpool-II/pgpool.conf"

- name: Template pcp.conf
  template: src=roles/db-pgpool/templates/pcp.conf.j2 dest="/etc/pgpool-II/pcp.conf"

- name: Template pgpool_failover.sh
  template: src=roles/db-pgpool/templates/pgpool_failover.sh.j2 dest="/usr/local/bin/pgpool_failover.sh" owner=root group=root mode=0750

- name: copy pool_hba.conf
  copy: src=roles/db-pgpool/files/pool_hba.conf dest="/etc/pgpool-II/pool_hba.conf" owner=root group=root mode=0644

- name: empty pool_passwd file
  file: dest=/etc/pgpool-II/pool_passwd state=touch owner=postgres group=postgres mode=640

- name: create pool_passwd file
  shell: /usr/bin/pg_md5 -u {{ item.edware_db_username }} -m {{ item.edware_db_password }}
  with_items: tenants

- name: Start PgPool
  service: name=pgpool state=started enabled=yes

- name: install pgpool_monitor.sh
  template: 
    src: roles/db-pgpool/templates/pgpool_monitor.sh.j2 
    dest: /usr/local/bin/pgpool_monitor.sh 
    mode: 0755
  tags:
    - pgpool-monitor

- name: install cron job
  copy: 
    src: roles/db-pgpool/files/pgpool_cron 
    dest: /etc/cron.d/pgpool_cron
  tags:
    - pgpool-monitor

