---
- name: Template pgpool.conf
  template: src=roles/edware/templates/pgpool.conf.j2 dest="/etc/pgpool-II-92/pgpool.conf"

- name: Start PgPool 
  service: name=pgpool-II-92 state=started enabled=yes
