---
- name: Stop PgPool 
  service: name=pgpool-II-92 state=stopped enabled=yes

- name: Template pgpool.conf
  template: src=roles/db-pgpool/templates/pgpool.conf.j2 dest="/etc/pgpool-II-92/pgpool.conf"

- name: Template pcp.conf
  template: src=roles/db-pgpool/templates/pcp.conf.j2 dest="/etc/pgpool-II-92/pcp.conf"

- name: Template pgpool_failover.sh
  template: src=role/db-pgpool/templates/pgpool_failover.sh.j2 dest="/usr/local/bin/pgpool_failover.sh" owner=root group=root mode=0750

- name: copy pool_hba.conf
  copy: src=role/db-pgpool/files/pool_hba.conf dest="/etc/pgpool-II-92/pool_hba.conf" owner=root group=root mode=0644

- name: Start PgPool 
  service: name=pgpool-II-92 state=started enabled=yes
