- name: install graphite and deps
  yum:
    name: "{{ item }}"
    state: present
  with_items: graphite_packages
  tags:
    - slow

- name: Remove rpm-provided wsgi config for graphite
  file:
    path: /etc/httpd/conf.d/graphite-web.conf
    state: absent
  notify: restart_httpd
  
- name: copy django/graphite settings
  template:
    src: local_settings.py.j2
    dest: "{{ graphite_conf }}/local_settings.py"
  notify: restart_httpd

- name: copy initial graphite data
  copy:
    src: graphite-dump.json
    dest: "{{ graphite_python }}/initial_data.json"
  
- name: find state of graphite db
  command:  "python {{ graphite_python }}/manage.py inspectdb"
  register: graphite_db_result
  changed_when: False

- name: prep graphite db, first pass 
  command: "python {{ graphite_python }}/manage.py syncdb --noinput"
  when: graphite_db_result.stdout.find('account_mygraph') == -1

# For terrible unknown reasons, this is needed 
# see http://stackoverflow.com/questions/28909061/django-graphite-integrityerror-column-username-is-not-unique
- name: prep graphite db, second pass 
  command: "python {{ graphite_python }}/manage.py syncdb --noinput"
  when: graphite_db_result.stdout.find('account_mygraph') == -1

- name: load initial data
  command: "python {{ graphite_python }}/manage.py loaddata {{ graphite_python }}/initial_data.json"
  when: graphite_db_result.stdout.find('account_mygraph') == -1

- name: Make sure graphite user can write to db
  file:
    path: "{{ graphite_var }}/graphite.db"
    owner: "{{ graphite_user }}"
    group: "{{ graphite_user }}"
  notify: restart_httpd
  
