- name: install graphite and deps
  yum:
    name: "{{ item }}"
    state: present
  with_items: graphite_packages
  
- name: copy django/graphite settings
  template:
    src: local_settings.py.j2
    dest: "{{ graphite_conf }}/local_settings.py"
#  notify: restart_httpd

- name: copy initial graphite data
  copy:
    src: graphite-dump.json
    dest: "{{ graphite_python }}/initial_data.json"
  
- name: find state of graphite db
  command:  "python {{ graphite_python }}/manage.py inspectdb"
  register: graphite_db_result
  changed_when: False

- name: prep graphite db
  command: "python {{ graphite_python }}/manage.py syncdb --noinput"
  when: graphite_db_result.stdout.find('account_mygraph') == -1

- name: load initial data
  command: "python {{ graphite_python }}/manage.py loaddata {{ graphite_python }}/initial_data.json"
  when: graphite_db_result.stdout.find('account_mygraph') == -1
