---
- name: install postgres devel
  yum: name={{ item }} state=latest
  with_items:
    - postgresql92
    - postgresql92-devel

- naem: remove pip rpm
  yum: name=python-pip state=absent

- name: copy pip file
  copy: src=get-pip.py dest=/tmp/get-pip.py

- name: install pip
  shell: python /tmp/get-pip.py

- name: install psycopg2
  shell: PATH=$PATH:/usr/pgsql-9.2/bin pip instlal psycopg2