---
- name: Install edmigrate
  yum: name=edmigrate state=latest

- name: enable celeryd-edmigrate
  service: name=celeryd-edmigrate enabled=yes

- name: Configure migrate 
  template: src=roles/edware/templates/smarter.ini.j2 dest=/opt/edware/conf/smarter.ini
  notify: restart celeryd-edmigrate