---
- name: Install latest HPZ rpm
  yum: name=hpz state=latest
  notify: restart httpd

- name: Configure hpz-web 
  template: src=roles/edware/templates/hpz.ini.j2 dest=/opt/edware/conf/hpz.ini
  notify: restart httpd 

- name: Configure IDP sso
  copy: src=files/{{ ec2_tag_environment }}/idp_metadata.xml dest=/opt/edware/conf/idp_metadata.xml
  notify: restart httpd 

- name: Install mod_ssl
  yum: name=mod_ssl state=latest

- name: get appropriate SSL certs
  shell: 'aws s3 sync --sse s3://srl-{{ec2_tag_environment}}-apache-internal-ssl/hpz-web /etc/pki/tls/'

- name: Configure Apache SSL
  template: src=ssl.conf dest=/etc/httpd/conf.d/ssl.conf
  notify: restart httpd

- name: Configure wsgi_frs.conf
  template: src=wsgi_frs.conf dest=/etc/httpd/conf.d/wsgi_frs.conf
  notify: restart httpd

- name: Configure wsgi_swi.conf
  template: src=wsgi_swi.conf dest=/etc/httpd/conf.d/wsgi_swi.conf
  notify: restart httpd
