---
- name: Configure tsb-worker
  template: src=roles/edware/templates/smarter_score_batcher.ini.j2 dest=/opt/edware/conf/smarter_score_batcher.ini
  notify: restart celeryd-smarter_score_batcher 

- name: create gpg directory
  file: 
    path: /dev/shm/celery/gpg 
    state: directory 
    owner: celery
    group: celery
    mode: 0700

- name: create celery directory
  file: 
    path: /dev/shm/celery 
    state: directory 
    owner: celery
    group: celery
    mode: 0700

- name: move private key to celery directory
  copy: src=tsb_smarterbalanced_org.key dest=/dev/shm/celery/tsb_smarterbalanced_org.key

- name: move public key to celery directory
  copy: src=tsb_smarterbalanced_org.pub dest=/dev/shm/celery/tsb_smarterbalanced_org.pub

- name: import private key
  shell: "gpg --homedir /dev/shm/celery/gpg --allow-secret-key-import --import /dev/shm/celery/tsb_smarterbalanced_org.key"

- name: import public key
  shell: "gpg --homedir /dev/shm/celery/gpg --import /dev/shm/celery/tsb_smarterbalanced_org.pub"

- name: delete private key
  shell: "rm roles/tsb/files/tsb_smarterbalanced_org.key && rm /dev/shm/celery/tsb_smarterbalanced_org.key"