---

- name: Select environment variable set
  include_vars: selector.yml

- name: Include the variables specific to the vpc
  include_vars: envs/{{ env_file }}.yml

- name: Create VPC 
  ec2_vpc:
    aws_access_key: "{{ aws_access_id }}"
    aws_secret_key: "{{ aws_secret_key }}"
    state: present
    cidr_block: "{{ vpc_cidr_block }}" 
    resource_tags: "{{ vpc_resource_tags }}" 
    subnets: "{{ vpc_subnets }}"
    internet_gateway: "{{ vpc_internet_gateway| default('True') }}" 
    route_tables: "{{ vpc_route_tables }}"
    region: "{{ vpc_region }}" 
    wait: yes 
  register: vpc
