---
  - name: stop PostgreSQL
    service: name=postgresql-9.2 state=stopped

  - name: clean up database directory
    shell: rm -rf /var/lib/pgsql/9.2/data/*

  - name: clean up database archive directory
    shell: rm -rf /var/lib/pgsql/9.2/archive/*

  - name: configure repmgr.conf
    template: src=roles/db-slave/templates/repmgr.conf.j2 dest=/var/lib/pgsql/repmgr.conf

  - name: place password
    copy: content="{{ reporting_db_master_ip }}:5432:edware:edware:{{ edware_db_ca_password }}" dest=/var/lib/pgsql/.pgpass owner=postgres group=postgres mode=0600

  - name: clone master
    shell: "su - postgres -c 'PATH=$PATH:/usr/pgsql-9.2/bin repmgr -D /var/lib/pgsql/9.2/data -d edware -p 5432 -R postgres --verbose standby clone {{ reporting_db_master_ip }}'"

  - name: recovery.conf file
    template: src=roles/db-slave/templates/recovery.conf.j2 dest=/var/lib/pgsql/9.2/data/recovery.conf

  - name: copy archive
    shell: "su - postgres -c 'scp {{ reporting_db_master_ip }}:/var/lib/pgsql/9.2/archive/* /var/lib/pgsql/9.2/archive/'"

  - name: start PostgreSQL
    service: name=postgresql-9.2 state=started

  - name: register slave
    shell: "su - postgres -c 'PATH=$PATH:/usr/pgsql-9.2/bin repmgr -f /var/lib/pgsql/repmgr.conf standby register'"

  - name: add service
    service: name=repmgrd state=started enabled=yes