---
- name: stop PostgreSQL
  service: name=postgresql-9.2 state=stopped

- name: Install postgresql92-contrib
  yum: name=postgresql92-contrib state=latest

- name: clean up database directory
  shell: rm -rf /var/lib/pgsql/9.2/data/*

- name: clean up database archive directory
  shell: rm -rf /var/lib/pgsql/9.2/archive/*

- name: place repmgr password
  copy: content="*:5432:*:repmgr:{{ edware_db_repmgr_password }}" dest=/var/lib/pgsql/.pgpass owner=postgres group=postgres mode=0600

- name: configure repmgr.conf
  template: src=roles/db-slave/templates/repmgr.conf.j2 dest=/var/lib/pgsql/repmgr.conf

- name: clone master
  shell: "su - postgres -c 'PATH=$PATH:/usr/pgsql-9.2/bin repmgr -D /var/lib/pgsql/9.2/data -U repmgr -d edware -p 5432 -R postgres --verbose --force standby clone {{ reporting_db_master_ip }}'"

- name: copy archive
  shell: "su - postgres -c 'scp {{ reporting_db_master_ip }}:/var/lib/pgsql/9.2/archive/* /var/lib/pgsql/9.2/archive/'"

- name: recovery.conf file
  template: src=roles/db-slave/templates/recovery.conf.j2 dest=/var/lib/pgsql/9.2/data/recovery.conf

- name: start PostgreSQL
  service: name=postgresql-9.2 state=started

- name: register slave
  shell: "su - postgres -c 'PATH=$PATH:/usr/pgsql-9.2/bin repmgr -f /var/lib/pgsql/repmgr.conf --force standby register'"
  ignore_errors: yes

- name: install wal_rsync.sh
  template: src=roles/db-slave/templates/wal_rsync.sh.j2 dest=/usr/local/bin/wal_rsync.sh mode=0755 owner=postgres group=postgres

- name: install cron job
  copy: src=roles/db-slave/files/wal_rsync_cron dest=/etc/cron.d/wal_rsync_cron
