---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    instance_ids:
      - 'i-5d6fd2ac'
      - 'i-5c6fd2ad'
    region: 'us-east-1'
    aws_access_key: "{{ lookup('pipe', 'pass dev/aws/access_id') }}"
    aws_secret_key: "{{ lookup('pipe', 'pass dev/aws/secret_key') }}"

  tasks:
    - name: provision ebs storage on srl-gluster-1
      local_action:
        module: ec2_vol
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        instance: 'i-5d6fd2ac'
        device_name: "/dev/{{ item.dev }}"
        volume_size: "{{ item.size }}"
        state: present
        encrypted: yes
        region: "{{ region }}"
      with_items:
        - { name: data1, size: 50, dev: xvdf }
        - { name: data2, size: 50, dev: xvdg }
        - { name: working1, size: 50, dev: xvdh }
        - { name: working2, size: 50, dev: xvdi }
        - { name: tsb1, size: 50, dev: xvdj }
        - { name: tsb2, size: 50, dev: xvdk }
        - { name: uploads1, size: 50, dev: xvdl }
        - { name: uploads2, size: 50, dev: xvdm }
        - { name: zones1, size: 50, dev: xvdn }
        - { name: zones2, size: 50, dev: xvdo }
      register: vols
    - name: tag volumes
      debug: msg="{{ item.volume_id }}"
      with_items: vols.results
    - name: provision ebs storage on srl-gluster-2
      ec2_vol:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        instance: 'i-5c6fd2ad'
        device_name: "/dev/{{ item.dev }}"
        volume_size: "{{ item.size }}"
        state: present
        encrypted: yes
        region: "{{ region }}"
      with_items:
        - { name: data1, size: 50, dev: xvdf }
        - { name: data2, size: 50, dev: xvdg }
        - { name: working1, size: 50, dev: xvdh }
        - { name: working2, size: 50, dev: xvdi }
        - { name: tsb1, size: 50, dev: xvdj }
        - { name: tsb2, size: 50, dev: xvdk }
        - { name: uploads1, size: 50, dev: xvdl }
        - { name: uploads2, size: 50, dev: xvdm }
        - { name: zones1, size: 50, dev: xvdn }
        - { name: zones2, size: 50, dev: xvdo }
      register: vols
