---
- name: Install packages required for GlusterFS client
  yum: name={{item}} state=latest
  with_items:
    - glusterfs
    - fuse
    - fuse-libs
    - glusterfs-fuse
    - nfs-utils
    - attr
  tags:
    - slow