sensu_checks:

  # ================================================ #
  #                common - metrics
  # ================================================ #
  disk-capacity-metrics: 
    type: metric
    handlers: 
      - store_in_carbon
    command: "/etc/sensu/plugins/disk-capacity-metrics.rb "
    interval: 300
    subscribers:
      - common

  # ================================================ #
  #                  heartbeats
  # ================================================ #
  lz-ssh-hearbeat:
    type: metric
    output_type: nagios_check
    handlers:
      - store_in_carbon
      # TODO add pagerduty
    interval: 10
    command: "/etc/sensu/plugins/check-banner.rb -h {{ lz_host }}"
    subscribers: 
      - heartbeats
