sensu_checks:

  # ================================================ #
  #                common - metrics
  # ================================================ #
  cpu-metrics: 
    type: metric
    handlers: 
      - store_in_carbon
    command: "/etc/sensu/plugins/cpu-metrics.rb --scheme sys.:::name:::.cpu"
    interval: 300
    subscribers: # == monitoring_topics
      - common

  disk-capacity-metrics: 
    type: metric
    handlers: 
      - store_in_carbon
    command: "/etc/sensu/plugins/disk-capacity-metrics.rb --scheme sys.:::name:::.disk"
    interval: 300
    subscribers: # == monitoring_topics
      - common

  load-metrics: 
    type: metric
    handlers: 
      - store_in_carbon
    command: "/etc/sensu/plugins/load-metrics.rb --scheme sys.:::name:::.load"
    interval: 300
    subscribers: # == monitoring_topics
      - common

  memory-metrics: 
    type: metric
    handlers: 
      - store_in_carbon
    command: "/etc/sensu/plugins/memory-metrics.rb --scheme sys.:::name:::.memory"
    interval: 300
    subscribers: # == monitoring_topics
      - common

  # ================================================ #
  #                  heartbeats
  # ================================================ #
  check.lz.heartbeat.sshbanner:
    type: check
    handlers:
      - pagerduty
    interval: 30
    command: "/etc/sensu/plugins/check-banner.rb -h {{ lz_host }}"
    subscribers: 
      - heartbeats # == monitoring_topics

  lz.heartbeat.sshbanner:
    type: metric
    output_type: nagios_check
    prefix: app
    auto_tag_host: 'no'
    handlers:
      - store_in_carbon
    interval: 30
    command: "/etc/sensu/plugins/check-banner.rb -h {{ lz_host }}"
    subscribers: 
      - heartbeats # == monitoring_topics

  check.reportingweb.heartbeat.simple:
    type: check
    handlers:
      - pagerduty
    interval: 30
    command: "/etc/sensu/plugins/check-http.rb -u {{ reporting_base_url_host }}/services/heartbeat --response_code 200"
    subscribers: 
      - heartbeats # == monitoring_topics

  reportingweb.heartbeat.simple:
    type: metric
    output_type: nagios_check
    prefix: app
    auto_tag_host: 'no'
    handlers:
      - store_in_carbon
    interval: 30
    command: "/etc/sensu/plugins/check-http.rb -u {{ reporting_base_url_host }}/services/heartbeat --response_code 200"
    subscribers: 
      - heartbeats # == monitoring_topics

  check.tsbweb.heartbeat.simple:
    type: check
    handlers:
      - pagerduty
    interval: 30
    command: "/etc/sensu/plugins/check-http.rb -u {{ tsb_base_url_host }}/services/heartbeat --response_code 200"
    subscribers: 
      - heartbeats # == monitoring_topics

  tsbweb.heartbeat.simple:
    type: metric
    output_type: nagios_check
    prefix: app
    auto_tag_host: 'no'
    handlers:
      - store_in_carbon
    interval: 30
    command: "/etc/sensu/plugins/check-http.rb -u {{ tsb_base_url_host }}/services/heartbeat --response_code 200"
    subscribers: 
      - heartbeats # == monitoring_topics

  zones.glusterfs.mount.simple:
    type: check
    handlers:
      - pagerduty
    interval: 60
    command: "/bin/ls /opt/edware/zones"
    subscribers:
      - zones_glusterfs

  pdf.glusterfs.mount.simple:
    type: check
    handlers:
      - pagerduty
    interval: 60
    command: "/bin/ls /opt/edware/pdf"
    subscribers:
      - pdf_glusterfs

  data.item.glusterfs.mount.simple:
    type: check
    handlers:
      - pagerduty
    interval: 60
    command: "/bin/ls /opt/edware/data/item_level"
    subscribers:
      - data_item_glusterfs

  data.raw.glusterfs.mount.simple:
    type: check
    handlers:
      - pagerduty
    interval: 60
    command: "/bin/ls /opt/edware/data/raw_data"
    subscribers:
      - data_raw_glusterfs
