---
# defaults file for ansible-graphite
graphite_log_rendering_performance: no
graphite_log_cache_performance: no
graphite_log_metric_access: no
graphite_timezone: UTC

graphite_packages:
  - graphite-web
  - python-carbon
  - python-yaml
  - libselinux-python
  - sqlite

graphite_conf: /etc/graphite-web
graphite_content_dir: /usr/share/graphite/webapp/content
graphite_index_file: "{{ graphite_var }}/search_index"
graphite_log_dir: /var/log/graphite-web
graphite_python: /usr/lib/python2.6/site-packages/graphite
graphite_storage_dir: "{{ carbon_local_data_dir }}"
graphite_user: apache
graphite_var: /var/lib/graphite-web
graphite_whisper_dir: "{{ carbon_local_data_dir }}"
graphite_htpasswd_username: srl-monitoring
