---
- name: Configure lz 
  template: src=roles/edware/templates/smarter.ini.j2 dest=/opt/edware/conf/smarter.ini

- name: Add authorized key
  authorized_key: user=root
                  key="{{ item }}"
  with_file:
    - files/{{ ec2_tag_environment }}/file-grabber-ssh.pub
