---
- include_vars: tsb-trigger.yml
- name: Configure tsb-trigger
  template: src=roles/edware/templates/smarter_score_batcher.ini.j2 dest=/opt/edware/conf/smarter_score_batcher.ini
  notify: restart file-monitor-smarter_score_batcher

- name: create gpg directory
  file: 
    path: /dev/shm/celery/gpg 
    state: directory 
    owner: celery
    group: celery
    mode: 0700

- name: create celery directory
  file: 
    path: /dev/shm/celery 
    state: directory 
    owner: celery
    group: celery
    mode: 0700
    
- name: create gpg directory
  file: 
    path: /opt/edware/gpg 
    state: directory 
    owner: celery
    group: celery
    mode: 0700

- name: move private key to celery directory
  copy: src=tsb_smarterbalanced_org.key dest=/dev/shm/celery/tsb_smarterbalanced_org.key owner=celery group=celery mode=0600

- name: move public key to celery directory
  copy: src=tsb_smarterbalanced_org.pub dest=/dev/shm/celery/tsb_smarterbalanced_org.pub owner=celery group=celery mode=0600

- name: move udl public key to celery directory
  copy: src=../../udl/files/sbac_smarterbalanced_org.pub dest=/dev/shm/celery/sbac_smarterbalanced_org.pub owner=celery group=celery mode=0600

- name: copy passphrase
  copy: content={{ tsb_passphrase }} dest=/dev/shm/celery/passphrase owner=celery group=celery mode=0600

- name: decrypt private key
  shell: openssl aes-256-cbc -salt -a -d -in /dev/shm/celery/tsb_smarterbalanced_org.key -out /dev/shm/celery/d_tsb_smarterbalanced_org.key -k {{ gpg_openssl_key }}

- name: import private key
  shell: 'su - celery -c "gpg --homedir /opt/edware/gpg  --allow-secret-key-import --import /dev/shm/celery/d_tsb_smarterbalanced_org.key"'
  ignore_errors: yes

- name: import public key
  shell: 'su - celery -c "gpg --homedir /opt/edware/gpg  --import /dev/shm/celery/tsb_smarterbalanced_org.pub"'
  ignore_errors: yes

- name: import udl public key
  shell: 'su - celery -c "gpg --homedir /opt/edware/gpg  --import /dev/shm/celery/sbac_smarterbalanced_org.pub"'
  ignore_errors: yes

- name: sign udl public key
  shell: 'su - celery -c "gpg --homedir /opt/edware/gpg --batch --yes --passphrase-file /dev/shm/celery/passphrase --edit-key sbac@smarterbalanced.org sign"'

- name: delete temporary gpg files
  file: path=/dev/shm/celery state=absent 
  