- name: srl-default security group
  ec2_group:
    name: srl-default
    aws_access_key: "{{ aws_access_id }}"
    aws_secret_key: "{{ aws_secret_key }}"
    description: Default security group for all instances
    vpc_id: "{{ vpc.vpc_id }}"
    region: "{{ vpc_region }}"
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 38.117.159.162/32
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 38.117.157.251/32
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: "{{ vpc_cidr_block }}"
    rules_egress:
      - proto: all
        from_port: all
        to_port: all
        cidr_ip: 0.0.0.0/0
    purge_rules: true
    purge_rules_egress: true
- name: srl-bind security group
  ec2_group:
    name: srl-bind
    aws_access_key: "{{ aws_access_id }}"
    aws_secret_key: "{{ aws_secret_key }}"
    description: BIND Servers
    vpc_id: "{{ vpc.vpc_id }}"
    region: "{{ vpc_region }}"
    rules:
      - proto: udp 
        from_port: 53
        to_port: 53
        cidr_ip: 10.0.0.0/8
    rules_egress:
- name: srl-db security group
  ec2_group:
    name: srl-db
    aws_access_key: "{{ aws_access_id }}"
    aws_secret_key: "{{ aws_secret_key }}"
    description: DB Servers
    vpc_id: "{{ vpc.vpc_id }}"
    region: "{{ vpc_region }}"
    rules:
      - proto: tcp
        from_port: 5432
        to_port: 5432
        cidr_ip: 10.0.0.0/8
    rules_egress:
    purge_rules: true
    purge_rules_egress: true
- name: srl-db-client security group
  ec2_group:
    name: srl-db-client
    aws_access_key: "{{ aws_access_id }}"
    aws_secret_key: "{{ aws_secret_key }}"
    description: Allow DB client access
    vpc_id: "{{ vpc.vpc_id }}"
    region: "{{ vpc_region }}"
    rules:
    rules_egress:
      - proto: tcp
        from_port: 5432
        to_port: 5432
        cidr_ip: 10.0.0.0/8
    purge_rules: true
    purge_rules_egress: true
- name: srl-db-pgbouncer security group
  ec2_group:
    name: srl-db-pgbouncer
    aws_access_key: "{{ aws_access_id }}"
    aws_secret_key: "{{ aws_secret_key }}"
    description: Allow pgbouncer client access
    vpc_id: "{{ vpc.vpc_id }}"
    region: "{{ vpc_region }}"
    rules:
    rules_egress:
      - proto: tcp
        from_port: 6432
        to_port: 6432
        cidr_ip: 10.0.0.0/8
      - proto: tcp
        from_port: 9999
        to_port: 9999
        cidr_ip: 10.0.0.0/8
    purge_rules: true
    purge_rules_egress: true
- name: srl-db-pool security group
  ec2_group:
    name: srl-db-pool
    aws_access_key: "{{ aws_access_id }}"
    aws_secret_key: "{{ aws_secret_key }}"
    description: Allow DB Pool access
    vpc_id: "{{ vpc.vpc_id }}"
    region: "{{ vpc_region }}"
    rules:
      - proto: tcp
        from_port: 9898
        to_port: 9898
        cidr_ip: 10.0.0.0/8
      - proto: tcp
        from_port: 9999
        to_port: 9999
        cidr_ip: 10.0.0.0/8
    rules_egress:
      - proto: tcp
        from_port: 9898
        to_port: 9898
        cidr_ip: 10.0.0.0/8
      - proto: tcp
        from_port: 9999
        to_port: 9999
        cidr_ip: 10.0.0.0/8
    purge_rules: true
    purge_rules_egress: true
- name: srl-db-pool-client security group
  ec2_group:
    name: srl-db-pool-client
    aws_access_key: "{{ aws_access_id }}"
    aws_secret_key: "{{ aws_secret_key }}"
    description: Allow DB Pool client access
    vpc_id: "{{ vpc.vpc_id }}"
    region: "{{ vpc_region }}"
    rules:
    rules_egress:
      - proto: tcp
        from_port: 6432
        to_port: 6432
        cidr_ip: 10.0.0.0/8
    purge_rules: true
    purge_rules_egress: true
- name: srl-db-pool-pcp security group
  ec2_group:
    name: srl-db-pool-pcp
    aws_access_key: "{{ aws_access_id }}"
    aws_secret_key: "{{ aws_secret_key }}"
    description: Allow DB Pool PCP access
    vpc_id: "{{ vpc.vpc_id }}"
    region: "{{ vpc_region }}"
    rules:
    rules_egress:
      - proto: tcp
        from_port: 9898
        to_port: 9898
        cidr_ip: 10.0.0.0/8
    purge_rules: true
    purge_rules_egress: true
- name: srl-glusterfs security group
  ec2_group:
    name: srl-glusterfs
    aws_access_key: "{{ aws_access_id }}"
    aws_secret_key: "{{ aws_secret_key }}"
    description: Allow GlusterFS access
    vpc_id: "{{ vpc.vpc_id }}"
    region: "{{ vpc_region }}"
    rules:
      - proto: tcp
        from_port: 111
        to_port: 111
        cidr_ip: 10.0.0.0/8
      - proto: tcp
        from_port: 24007
        to_port: 24007
        cidr_ip: 10.0.0.0/8
      - proto: tcp
        from_port: 49152
        to_port: 49164
        cidr_ip: 10.0.0.0/8
    rules_egress:
      - proto: tcp
        from_port: 111
        to_port: 111
        cidr_ip: 10.0.0.0/8
      - proto: tcp
        from_port: 24007
        to_port: 24007
        cidr_ip: 10.0.0.0/8
      - proto: tcp
        from_port: 49152
        to_port: 49164
        cidr_ip: 10.0.0.0/8
      
    purge_rules: true
    purge_rules_egress: true
- name: srl-glusterfs-pdf-client security group
  ec2_group:
    name: srl-glusterfs-pdf-client
    aws_access_key: "{{ aws_access_id }}"
    aws_secret_key: "{{ aws_secret_key }}"
    description: Allow GlusterFS access
    vpc_id: "{{ vpc.vpc_id }}"
    region: "{{ vpc_region }}"
    rules:
      - proto: tcp
        from_port: 111
        to_port: 111
        cidr_ip: 10.0.0.0/8
      - proto: tcp
        from_port: 24007
        to_port: 24007
        cidr_ip: 10.0.0.0/8
      - proto: tcp
        from_port: 49162
        to_port: 49163
        cidr_ip: 10.0.0.0/8
    rules_egress:
      - proto: tcp
        from_port: 111
        to_port: 111
        cidr_ip: 10.0.0.0/8
      - proto: tcp
        from_port: 24007
        to_port: 24007
        cidr_ip: 10.0.0.0/8
      - proto: tcp
        from_port: 49162
        to_port: 49163
        cidr_ip: 10.0.0.0/8
    purge_rules: true
    purge_rules_egress: true
- name: srl-glusterfs-extract-client security group
  ec2_group:
    name: srl-glusterfs-extract-client
    aws_access_key: "{{ aws_access_id }}"
    aws_secret_key: "{{ aws_secret_key }}"
    description: Allow GlusterFS access
    vpc_id: "{{ vpc.vpc_id }}"
    region: "{{ vpc_region }}"
    rules:
      - proto: tcp
        from_port: 111
        to_port: 111
        cidr_ip: 10.0.0.0/8
      - proto: tcp
        from_port: 24007
        to_port: 24007
        cidr_ip: 10.0.0.0/8
      - proto: tcp
        from_port: 49152
        to_port: 49155
        cidr_ip: 10.0.0.0/8
    rules_egress:
      - proto: tcp
        from_port: 111
        to_port: 111
        cidr_ip: 10.0.0.0/8
      - proto: tcp
        from_port: 24007
        to_port: 24007
        cidr_ip: 10.0.0.0/8
      - proto: tcp
        from_port: 49152
        to_port: 49155
        cidr_ip: 10.0.0.0/8
    purge_rules: true
    purge_rules_egress: true
- name: srl-glusterfs-udl-client security group
  ec2_group:
    name: srl-glusterfs-udl-client
    aws_access_key: "{{ aws_access_id }}"
    aws_secret_key: "{{ aws_secret_key }}"
    description: Allow GlusterFS access
    vpc_id: "{{ vpc.vpc_id }}"
    region: "{{ vpc_region }}"
    rules:
      - proto: tcp
        from_port: 111
        to_port: 111
        cidr_ip: 10.0.0.0/8
      - proto: tcp
        from_port: 24007
        to_port: 24007
        cidr_ip: 10.0.0.0/8
      - proto: tcp
        from_port: 49156
        to_port: 49156
        cidr_ip: 10.0.0.0/8
      - proto: tcp
        from_port: 49157
        to_port: 49157
        cidr_ip: 10.0.0.0/8
    rules_egress:
      - proto: tcp
        from_port: 111
        to_port: 111
        cidr_ip: 10.0.0.0/8
      - proto: tcp
        from_port: 24007
        to_port: 24007
        cidr_ip: 10.0.0.0/8
      - proto: tcp
        from_port: 49156
        to_port: 49156
        cidr_ip: 10.0.0.0/8
      - proto: tcp
        from_port: 49157
        to_port: 49157
        cidr_ip: 10.0.0.0/8
    purge_rules: true
    purge_rules_egress: true
- name: srl-glusterfs-hpz-client security group
  ec2_group:
    name: srl-glusterfs-hpz-client
    aws_access_key: "{{ aws_access_id }}"
    aws_secret_key: "{{ aws_secret_key }}"
    description: Allow GlusterFS access
    vpc_id: "{{ vpc.vpc_id }}"
    region: "{{ vpc_region }}"
    rules:
      - proto: tcp
        from_port: 111
        to_port: 111
        cidr_ip: 10.0.0.0/8
      - proto: tcp
        from_port: 24007
        to_port: 24007
        cidr_ip: 10.0.0.0/8
      - proto: tcp
        from_port: 49158
        to_port: 49158
        cidr_ip: 10.0.0.0/8
      - proto: tcp
        from_port: 49159
        to_port: 49159
        cidr_ip: 10.0.0.0/8
    rules_egress:
      - proto: tcp
        from_port: 111
        to_port: 111
        cidr_ip: 10.0.0.0/8
      - proto: tcp
        from_port: 24007
        to_port: 24007
        cidr_ip: 10.0.0.0/8
      - proto: tcp
        from_port: 49158
        to_port: 49158
        cidr_ip: 10.0.0.0/8
      - proto: tcp
        from_port: 49159
        to_port: 49159
        cidr_ip: 10.0.0.0/8
    purge_rules: true
    purge_rules_egress: true
- name: srl-logging security group
  ec2_group:
    name: srl-logging
    aws_access_key: "{{ aws_access_id }}"
    aws_secret_key: "{{ aws_secret_key }}"
    description: Allow Log Server client access
    vpc_id: "{{ vpc.vpc_id }}"
    region: "{{ vpc_region }}"
    rules:
    rules_egress:
      - proto: tcp
        from_port: 10514
        to_port: 10514
        cidr_ip: 10.0.0.0/8
    purge_rules: true
    purge_rules_egress: true
- name: srl-logstash security group
  ec2_group:
    name: srl-logstash
    aws_access_key: "{{ aws_access_id }}"
    aws_secret_key: "{{ aws_secret_key }}"
    description: Allow Log Server access
    vpc_id: "{{ vpc.vpc_id }}"
    region: "{{ vpc_region }}"
    rules:
      - proto: tcp
        from_port: 9200
        to_port: 9200
        cidr_ip: 10.0.0.0/8
      - proto: tcp
        from_port: 10514
        to_port: 10514
        cidr_ip: 10.0.0.0/8
    rules_egress:
    purge_rules: true
    purge_rules_egress: true
- name: srl-memcached security group
  ec2_group:
    name: srl-memcached
    aws_access_key: "{{ aws_access_id }}"
    aws_secret_key: "{{ aws_secret_key }}"
    description: Allow Memcache access
    vpc_id: "{{ vpc.vpc_id }}"
    region: "{{ vpc_region }}"
    rules:
      - proto: tcp
        from_port: 11211
        to_port: 11211
        cidr_ip: 10.0.0.0/8
    rules_egress:
      - proto: tcp
        from_port: 11211
        to_port: 11211
        cidr_ip: 10.0.0.0/8
    purge_rules: true
    purge_rules_egress: true
- name: srl-nat security group
  when: "{{ environ != 'prod' }}"
  ec2_group:
    name: srl-nat
    aws_access_key: "{{ aws_access_id }}"
    aws_secret_key: "{{ aws_secret_key }}"
    description: Allow private subnet access to NAT for external inet traffic
    vpc_id: "{{ vpc.vpc_id }}"
    region: "{{ vpc_region }}"
    rules:
      - proto: all
        from_port: all
        to_port: all
        cidr_ip: 10.0.0.0/8
    rules_egress:
      - proto: all
        from_port: all
        to_port: all
        cidr_ip: 0.0.0.0/0
    purge_rules: true
    purge_rules_egress: true
- name: srl-rmq security group
  ec2_group:
    name: srl-rmq
    aws_access_key: "{{ aws_access_id }}"
    aws_secret_key: "{{ aws_secret_key }}"
    description: Allow RabbitMQ access
    vpc_id: "{{ vpc.vpc_id }}"
    region: "{{ vpc_region }}"
    rules:
      - proto: tcp
        from_port: 4369
        to_port: 4369
        cidr_ip: 10.0.0.0/8
      - proto: tcp
        from_port: 5671
        to_port: 5671
        cidr_ip: 10.0.0.0/8
    rules_egress:
    purge_rules: true
    purge_rules_egress: true
- name: srl-rmq-client security group
  ec2_group:
    name: srl-rmq-client
    aws_access_key: "{{ aws_access_id }}"
    aws_secret_key: "{{ aws_secret_key }}"
    description: Allow RabbitMQ client access
    vpc_id: "{{ vpc.vpc_id }}"
    region: "{{ vpc_region }}"
    rules:
    rules_egress:
      - proto: tcp
        from_port: 5671
        to_port: 5671
        cidr_ip: 10.0.0.0/8
    purge_rules: true
    purge_rules_egress: true
- name: srl-sso-client security group
  ec2_group:
    name: srl-sso-client
    aws_access_key: "{{ aws_access_id }}"
    aws_secret_key: "{{ aws_secret_key }}"
    description: Allow SSO client access
    vpc_id: "{{ vpc.vpc_id }}"
    region: "{{ vpc_region }}"
    rules:
    rules_egress:
      - proto: tcp
        from_port: 8443
        to_port: 8443
        cidr_ip: 10.0.0.0/8
    purge_rules: true
    purge_rules_egress: true
- name: srl-web security group
  ec2_group:
    name: srl-web
    aws_access_key: "{{ aws_access_id }}"
    aws_secret_key: "{{ aws_secret_key }}"
    description: Allow web server access
    vpc_id: "{{ vpc.vpc_id }}"
    region: "{{ vpc_region }}"
    rules:
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 10.0.0.0/8
      - proto: tcp
        from_port: 443
        to_port: 443
        cidr_ip: 10.0.0.0/8
    rules_egress:
    purge_rules: true
    purge_rules_egress: true
- name: srl-web-client security group
  ec2_group:
    name: srl-web-client
    aws_access_key: "{{ aws_access_id }}"
    aws_secret_key: "{{ aws_secret_key }}"
    description: Allow web server client access
    vpc_id: "{{ vpc.vpc_id }}"
    region: "{{ vpc_region }}"
    rules:
    rules_egress:
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/8
      - proto: tcp
        from_port: 443
        to_port: 443
        cidr_ip: 0.0.0.0/8
    purge_rules: true
    purge_rules_egress: true
- name: omniti-fulton-office security group
  ec2_group:
    name: omniti-fulton-office
    aws_access_key: "{{ aws_access_id }}"
    aws_secret_key: "{{ aws_secret_key }}"
    description: OmniTI Fulton secure office connection (two factor openvpn)
    vpc_id: "{{ vpc.vpc_id }}"
    region: "{{ vpc_region }}"
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 108.48.124.82/32
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 108.48.124.83/32
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 108.48.124.84/32
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 108.48.124.85/32
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 108.48.124.86/32
    rules_egress:
    purge_rules: true
    purge_rules_egress: true
- name: srl-elb security group
  ec2_group:
    name: srl-elb
    aws_access_key: "{{ aws_access_id }}"
    aws_secret_key: "{{ aws_secret_key }}"
    description: Allow ELB HTTP and HTTPS access
    vpc_id: "{{ vpc.vpc_id }}"
    region: "{{ vpc_region }}"
    rules:
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 10.0.0.0/0
      - proto: tcp
        from_port: 443
        to_port: 443
        cidr_ip: 10.0.0.0/0
    rules_egress:
    purge_rules: true
    purge_rules_egress: true
 - name: srl-elb-hpz
   ec2_group:
     name: srl-elb-hpz
     aws_access_key: "{{ aws_access_id }}"
     aws_secret_key: "{{ aws_secret_key }}"
     description: Allow ELB 8443 access internally for hpz-web 
     vpc_id: "{{ vpc.vpc_id }}"
     region: "{{ vpc_region }}"
     rules:
       - proto: tcp
         from_port: 8443 
         to_port: 8443
         cidr_ip: 54.165.82.75/32 #Prod NAT, template out for dev 
       - proto: tcp
         from_port: 8443
         to_port: 8443
         cidr_ip: 54.175.150.30/32 #Prod NAT, template out for dev 
     rules_egress:
     purge_rules: true
     purge_rules_egress: true
 - name: srl-hpz-web
   ec2_group:
     name: srl-hpz-web
     aws_access_key: "{{ aws_access_id }}"
     aws_secret_key: "{{ aws_secret_key }}"
     description: Allow 8443 access internally for hpz-web
     vpc_id: "{{ vpc.vpc_id }}"
     region: "{{ vpc_region }}"
     rules:
       - proto: tcp
         from_port: 8443
         to_port: 8443
         cidr_ip: 10.0.0.0/8
     rules_egress:
     purge_rules: true
     purge_rules_egress: true
