---
- include_vars: gluster-storage.yml
- name: provision ebs storage on gluster nodes
  local_action:
    module: ec2_vol
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    instance: "{{ hostvars[item[0]].ec2_id }}"
    device_name: "/dev/{{ item[1].dev }}"
    volume_size: "{{ item[1].size }}"
    state: present
    encrypted: yes
    region: "{{ region }}"
  with_nested:
    - groups['gluster-server']
    - storage_devices
  register: ec2_vols

- name: show me the vol ids
  debug:
    var: item.volume_id
  with_items: ec2_vols.results

- name: tag the volumes we just created 
  local_action: ec2_tag resource="{{ item.volume_id }}" state=present region="{{ region }}" aws_access_key="{{ aws_access_key }}" aws_secret_key="{{ aws_secret_key }}"
  with_items: ec2_vols.results
  args:
    tags:
      Name: gluster