b_block: "{{lookup('env', 'SBAC_ENVIRO_BUILDER_VPC_BLOCK')}}"
env_name: "{{lookup('env', 'SBAC_ENVIRO_BUILDER_ENV_NAME')}}"

vpc_cidr_block: 10.{{ b_block }}.48.0/20
vpc_resource_tags: { "Environment":"{{ env_name }}", "Name":"{{ env_name }} VPC" }
vpc_subnets:
  - cidr: 10.{{ b_block }}.48.0/22
    az: us-east-1c
    resource_tags: { "Environment":"{{ env_name }}", "Tier":"Public", "Name":"{{ env_name }}-Public" }
  - cidr: 10.{{ b_block }}.52.0/22
    az: us-east-1c
    resource_tags: { "Environment":"{{ env_name }}", "Tier":"Private", "Name":"{{ env_name }}-Private" }
  - cidr: 10.{{ b_block }}.56.0/22
    az: us-east-1c
    resource_tags: { "Environment":"{{ env_name }}", "Tier":"LZ", "Name":"{{ env_name }}-LZ" }
vpc_internet_gateway: True
vpc_route_tables:
          - subnets:
              - "10.{{ b_block }}.48.0/22"
              - "10.{{ b_block }}.52.0/22"
            routes:
              - dest: 0.0.0.0/0
                gw: igw
          - subnets:
              - "10.{{ b_block }}.56.0/22"
            routes:
              - dest: 0.0.0.0/0
                gw: igw
vpc_region: us-east-1
