vpc_cidr_block: 10.167.48.0/20
vpc_resource_tags: { "Environment":"stage", "Name":"Stage VPC" }
vpc_subnets:
  - cidr: 10.167.48.0/22
    az: us-east-1e
    resource_tags: { "Environment":"stage", "Tier":"Public", "Name":"Stage-Public" }
  - cidr: 10.167.52.0/22
    az: us-east-1e
    resource_tags: { "Environment":"stage", "Tier":"Private", "Name":"Stage-Private" }
  - cidr: 10.167.56.0/22
    az: us-east-1e
    resource_tags: { "Environment":"stage", "Tier":"LZ", "Name":"Stage-LZ" }
vpc_internet_gateway: True
vpc_route_tables:
          - subnets:
              - 10.167.48.0/22 # Public
              - 10.167.52.0/22 # Private
            routes:
              - dest: 0.0.0.0/0
                gw: igw
          - subnets:
              - 10.167.56.0/22 # LZ
            routes:
              - dest: 0.0.0.0/0
                gw: igw
vpc_region: us-east-1
