aws_access_key: "{{ aws_access_id }}"

storage_devices:
  - { name: data1, size: 50, dev: xvdf }
  - { name: data2, size: 50, dev: xvdg }
  - { name: working1, size: 50, dev: xvdh }
  - { name: working2, size: 50, dev: xvdi }
  - { name: tsb1, size: 50, dev: xvdj }
  - { name: tsb2, size: 50, dev: xvdk }
  - { name: uploads1, size: 50, dev: xvdl }
  - { name: uploads2, size: 50, dev: xvdm }
  - { name: zones1, size: 50, dev: xvdn }
  - { name: zones2, size: 50, dev: xvdo }
  - { name: pdf1, size: 50, dev: xvdp }
  - { name: pdf2, size: 50, dev: xvdq }
