wsgi_process_count: 2
install_python3: true
httpd_conf_templates:
  hpz-web:
    - ssl_on
    - xsendfile
    - wsgi_frs
    - wsgi_swi
  reporting-web:
    - edware_worker_mpm
    - response_metrics
    - rewrite_reporting_https # TODO: parameterize this file with hostname
    - rewrite_reporting_slash
    - ssl_main_server
    - wsgi_edware    
  tsb-web:
    - wsgi_tsb
    - ssl_main_server
    - rewrite_tsb  # TODO: parameterize this file with hostname
  sensu:
    - graphite-auth-file
    - ssl_main_server
    - wsgi_graphite

    
  
