wsgi_process_count: 2
httpd_conf_templates:
  hpz-web:
    - ssl_on
    - xsendfile
    - wsgi_frs
    - wsgi_swi
  reporting-web:
    - ssl_main_server
    - wsgi_edware
  tsb-web:
    - wsgi_tsb
    - ssl_main_server
    - rewrite_tsb  # TODO: parameterize this file with hostname
    
  
