---
- include_vars: gluster-server.yml

- name: Install packages required for GlusterFS
  yum: name={{item}} state=latest
  with_items:
    - fuse
    - fuse-libs
    - glusterfs-server
    - glusterfs-fuse
    - nfs-utils
  tags:
    - slow

- name: Enable and start required services
  service: name={{item}} state=started enabled=yes
  with_items:
    - glusterd
    - rpcbind 

- name: create base directory
  file: path=/export state=directory owner=root group=root mode=0600

- name: create brick mount points
  file: path=/export/{{ item.label }} state=directory owner=root group=root mode=0600
  with_items: brick_devices
  tags: 
    - slow

- name: create lvm volume groups
  lvg: pvs=/dev/{{ item.dev }} state=present vg=vg.{{ item.label }}
  with_items: brick_devices
  tags: 
    - slow

- name: create lvm logical volumes
  lvol: lv=lv.{{ item.label }} state=present vg=vg.{{ item.label }} size='100%VG'
  with_items: brick_devices
  tags: 
    - slow

- name: create brick file systems
  filesystem: fstype=ext4 dev=/dev/vg.{{ item.label }}/lv.{{ item.label }} opts="-m1 -L {{ item.label }}"
  with_items: brick_devices
  tags: 
    - slow

- name: add bricks to fstab and mount
  mount: fstype=ext4 name="/export/{{ item.label }}" src="LABEL={{ item.label }}" opts=noatime state=mounted
  with_items: brick_devices
  tags: 
    - slow

- name: create brick subdirs for volumes
  file: path=/export/{{ item.label }}/brick state=directory owner=root group=root mode=0600
  with_items: brick_devices

- name: sync server ssl certificates
  shell: "/usr/local/bin/aws s3 sync --sse s3://srl-{{ec2_tag_environment}}-gluster-ssl/gluster-server /etc/ssl --exclude 'certs/'"
  register: gluster_server_s3_sync
  changed_when: "gluster_server_s3_sync.stdout != ''"
  #notify:
  #  - restart gluster server

- name: check peering
  shell: "gluster peer probe {{ node2 }}"
  delegate_to: "{{ node1 }}"
  changed_when: false

- name: create volumes
  shell: 'gluster volume info {{ item }} | grep -q "Status: Started\|Created\|Stopped" || gluster volume create {{ item }} replica 2 transport tcp {{node1}}:/export/{{ item }}1/brick {{node2}}:/export/{{ item }}1/brick {{node1}}:/export/{{ item }}2/brick {{node2}}:/export/{{ item }}2/brick && sleep 5'
  with_items: volumes
  run_once: true
  delegate_to: "{{ node1 }}"
  register: gluster_server_create_out
  changed_when: "gluster_server_create_out.stdout != ''"

- name: configure volumes
  shell: 'gluster volume info {{ item.vol }} | grep -q "Status: Started\|Created" || gluster volume set {{item.vol}} nfs.disable on && gluster volume set {{item.vol}} client.ssl on && gluster volume set {{item.vol}} server.ssl on && gluster volume set {{item.vol}} performance.cache-size 256MB &&  gluster volume set {{ item.vol }} auth.ssl-allow {{ item.ssl }} && echo "I made changes"'
#  gluster volume set {{item.vol}} auth.allow '*' &&
  with_items: vol_ssl
  run_once: true
  delegate_to: "{{node1}}"
  register: gluster_server_config_out
  # TODO - this always shows changed, fix idempotency
  changed_when: "gluster_server_config_out.stdout != ''"

- name: start volumes
  shell: 'gluster volume info {{ item }} | grep -q "Status: Started" || gluster volume start {{item}}'
  run_once: true
  with_items: volumes
  delegate_to: "{{node1}}"
  register: gluster_server_start_out
  changed_when: "gluster_server_start_out.stdout != ''"
