---
- include_vars: gluster-client.yml

- name: Install packages required for GlusterFS client
  yum: name={{item}} state=latest
  with_items:
    - glusterfs
    - fuse
    - fuse-libs
    - glusterfs-fuse
    - nfs-utils
    - attr
  tags:
    - slow

# Commenting out only - in-case want to re-enable SSL in the future
#- name: get appropriate SSL certs
#  shell: '/usr/local/bin/aws s3 sync --sse --exact-timestamp s3://srl-{{ec2_tag_environment}}-gluster-ssl/{{gluster_mount[ec2_tag_application].subj}} /etc/ssl --exclude "certs/" '
#  register: gluster_client_s3_sync
#  changed_when: "gluster_client_s3_sync.stdout != ''"
  # TODO: notify to remount


- name: create mount point
  file: path={{ item.mount_at }} state=directory owner={{ item.owner }} group={{ item.group }} mode=0750
  with_items: gluster_mount[ec2_tag_application].mounts

- name: Ensure GlusterFS volume is mounted; add to fstab
  mount:
    fstype: glusterfs
    name: "{{ item.mount_at }}"
    src: "{{gfs_node1}}:/{{item.volume}}"
    opts: "noauto"
    state: mounted
  with_items: gluster_mount[ec2_tag_application].mounts
