---

#- name: Require VAR variable
#  fail:
#    msg: "You must provide the variable VAR as a playbook variable"
#  when: VAR is not defined

- name: Require sensu_checks variable
  fail:
    msg: "You must provide the variable sensu_checks as a playbook variable"
  when: sensu_install_server and (sensu_checks is not defined)

- name: Require sensu_handlers variable
  fail:
    msg: "You must provide the variable sensu_handlers as a playbook variable"
  when: sensu_install_server and (sensu_handlers is not defined)

- name: Require sensu_rabbit_host variable
  fail:
    msg: "You must provide the variable sensu_rabbit_host in group_vars/ENV/secrets.yml"
  when: sensu_rabbit_host is not defined

- name: Require sensu_rabbit_password variable
  fail:
    msg: "You must provide the variable sensu_rabbit_password in group_vars/ENV/secrets.yml"
  when: sensu_rabbit_password is not defined

- name: Require sensu_client_subscriptions variable
  fail:
    msg: "You must provide the variable sensu_client_subscriptions as a playbook variable"
    # TODO: validate it is an array
    # TODO: validate its members are from a restricted vocabulary
  when: sensu_install_client and (sensu_client_subscriptions is not defined)
