---

# Variables used to locate services.  

#-------------------------------------------------------------#
#                   Application Specific Config
#-------------------------------------------------------------#

# TODO
#sso_oauth_verify_url: http://sso.sbac2.net:8080/OpenAM-11.0.0/oauth2/tokeninfo?realm=/
auth_policy_secure: True
# TODO: neeed prod SSO
#sso_saml_login_url: http://sso.sbac2.net:8080/OpenAM-11.0.0/SSORedirect/metaAlias/idp
#sso_saml_logout_url: http://sso.sbac2.net:8080/OpenAM-11.0.0/IDPSloRedirect/metaAlias/idp
#sso_saml_issuer_name: http://srl-reporting-web
#sso_saml_name_qualifier: http://sso.sbac2.net:8080/OpenAM-11.0.0
#cache_hosts: srl-memcached.dev.ae1.sbac2dc.net:11211
#hpz_base_url: http://srl-hpz-web.dev.ae1.sbac2dc.net:8443
#reporting_base_url_host: http://srl-web-reporting.dev.ae1.sbac2dc.net
disable_stack_trace: True
