tenants:
  - name: ca
    schema_name: ca
    state_code: CA
    edware_db_username: "{{ edware_db_ca_username }}"
    edware_db_password: "{{ edware_db_ca_password }}"
    edware_db_host: "{{ hostvars | srl_hostvars_lookup((groups.get('reporting-db-pgpool', []) | intersect(locals) | first))['ec2_tag_Name'] }}.{{ domain }}"
    edware_db_port: 9999
  - name: ot
    schema_name: ot
    state_code: OT
    edware_db_username: "{{ edware_db_ca_username }}"
    edware_db_password: "{{ edware_db_ca_password }}"
    edware_db_host: "{{ hostvars | srl_hostvars_lookup((groups.get('reporting-db-pgpool', []) | intersect(locals) | first))['ec2_tag_Name'] }}.{{ domain }}"
    edware_db_port: 9999

migrate_tenants:
  - name: ca
    schema_name: ca
    migrate_dest_db_host: "{{ hostvars | srl_hostvars_lookup((groups.get('db-master', []) | intersect(locals) | first))['ec2_tag_Name'] }}.{{ domain }}"
    migrate_dest_db_username: "{{ migrate_dest_db_ca_username }}"
    migrate_dest_db_password: "{{ migrate_dest_db_ca_password }}"
    migrate_source_db_host: "{{ hostvars | srl_hostvars_lookup((groups.get('migrate-db', []) | intersect(locals) | first))['ec2_tag_Name'] }}.{{ domain }}"
    migrate_source_db_username: "{{ migrate_source_db_ca_username }}"
    migrate_source_db_password: "{{ migrate_source_db_ca_password }}"

staging_tenants:
  - name: ca
    staging_db_username: "{{ staging_db_ca_username }}"
    staging_db_password: "{{ staging_db_ca_password }}"
    staging_db_host: "{{ hostvars | srl_hostvars_lookup((groups.get('migrate-db', []) | intersect(locals) | first))['ec2_tag_Name'] }}.{{ domain }}"

public_tenants:
  - name: ca
    state_code: CA
    public_schema_name: public_ca
    public_edware_db_username: "{{ edware_db_ca_username }}"
    public_edware_db_password: "{{ edware_db_ca_username }}"
    public_edware_db_host: "{{ hostvars | srl_hostvars_lookup((groups.get('db-public', []) | intersect(locals) | first))['ec2_tag_Name'] }}.{{ domain }}"
    private_schema_name: ca
    private_edware_db_username: "{{ edware_db_ca_username }}"
    private_edware_db_password: "{{ edware_db_ca_username }}"
    private_edware_db_host: "{{ hostvars | srl_hostvars_lookup((groups.get('db-master', []) | intersect(locals) | first))['ec2_tag_Name'] }}.{{ domain }}"
    edware_db_port: 5432

extract_tenants:
  - name: ca
    schema_name: ca
    state_code: CA
    edware_db_username: "{{ edware_extract_db_ca_username }}"
    edware_db_password: "{{ edware_extract_db_ca_password }}"
    edware_db_host: "{{ hostvars | srl_hostvars_lookup((groups.get('extracts-db-pgpool', []) | intersect(locals) | first))['ec2_tag_Name'] }}.{{ domain }}"
    edware_db_port: 9999
  - name: ot
    schema_name: ot
    state_code: OT
    edware_db_username: "{{ edware_extract_db_ca_username }}"
    edware_db_password: "{{ edware_extract_db_ca_password }}"
    edware_db_host: "{{ hostvars | srl_hostvars_lookup((groups.get('extracts-db-pgpool', []) | intersect(locals) | first))['ec2_tag_Name'] }}.{{ domain }}"
    edware_db_port: 9999
