---
- name: Configure tsb-web 
  template: src=roles/edware/templates/smarter_score_batcher.ini.j2 dest=/opt/edware/conf/smarter_score_batcher.ini
  notify: restart httpd 

- name: Install mod_ssl
  yum: name=mod_ssl state=latest

- name: get appropriate SSL certs
  shell: 'aws s3 sync --sse s3://srl-{{ec2_tag_environment}}-apache-internal-ssl/tsb-web /etc/pki/tls/'

- name: Configure Apache SSL
  file: src=ssl.conf dest=/etc/httpd/conf.d/ssl.conf
  notify: restart httpd
