- name: Prep an instance for cutting a new Ansible AMI
  hosts: tag_ami-builder_ansible
  sudo: yes
  gather_facts: no
  vars:
    ansible_users:
      - ansible
  roles:
    # - common
    - ansible
    - ansible-bootstrap
