---
- name: Configure the standalone database postgres server 
  hosts: db-master
  user: ansible
  sudo: yes

  roles:
    - common
    - db
    - { role: db-master, tags: ['db-master', 'app'] }
    - migrate-conductor

# We might need to update postgres user names and password
