---
- name: Configure the standalone database postgres server 
  hosts: db-master
  user: ansible
  sudo: yes
  vars:
    monitoring_topics:
      common
      
  roles:
    - { role: common, tags:['common']}
    - { role: db, tags: ['db', 'app'] }
    - { role: db-master, tags: ['db-master', 'app'] }
    # TODO: We need to update postgres user names and password
    - { role: migrate-conductor, tags: ['migrate-conductor', 'app'] }
    - { role: sensu, tags: ['sensu', 'monitoring'] }
