---
- name: Configure file-trigger server 
  hosts: file-trigger 
  user: ansible
  sudo: yes
  vars:
    edware_rpm_name: edudl2
    monitoring_topics:
      - common 
      - zones_glusterfs

  roles:
    - { role: common, tags: ['common']}
    - { role: edware, tags: ['edware', 'app'] }
    - { role: gluster-client, tags: ['gluster-client'] }
    - { role: file-trigger, tags: ['file-trigger', 'app']}
    - { role: sensu, tags: ['sensu', 'monitoring'] }
