---
- name: Configure file-grabber server 
  hosts: file-grabber 
  user: ansible
  sudo: yes

  roles:
    - common
    - edware
    - { role: gluster-client, tags: ['gluster-client'] }
    - file-grabber
