---
- name: Configure file-grabber server 
  hosts: file-grabber 
  sudo: yes
  vars:
    monitoring_topics:
      - common 

  roles:
    - { role: aws-cli, tags: ['aws-cli'] }
    - { role: gluster-client, tags: ['gluster-client'] }
    - { role: common, tags:['common']}
    - { role: edware, tags: ['edware', 'app'] }
    - { role: file-grabber, tags: ['file-grabber', 'app']}
    - { role: sensu, tags: ['sensu', 'monitoring'] }
