---
- name: Configure file-grabber server 
  hosts: file-grabber 
  user: ansible
  sudo: yes
  vars:
    monitoring_topics:
      - common 
      - zones_glusterfs

  pre_tasks:
    - include: roles/udl/tasks/user.yml

  roles:
    - { role: common, tags: ['common']}
    - { role: edware, tags: ['edware', 'app'] }
    - { role: gluster-client, tags: ['gluster-client'] }
    - { role: file-grabber, tags: ['file-grabber', 'app']}
    - { role: sensu, tags: ['sensu', 'monitoring'] }
