---
- name: Configure file-trigger server 
  hosts: file-trigger 
  user: ansible
  sudo: yes

  roles:
    - common
    - edware
    - { role: aws-cli, tags: ['aws-cli'] }
    - { role: gluster-client, tags: ['gluster-client'] }
    - file-trigger 
