- name: Generic rabbitmq setup
  hosts: migrate-rabbit:reporting-rabbit-services:reporting-rabbit-extract:tsb-rabbit:udl-rabbit
  sudo: yes
  vars:
    monitoring_topics:
      - common 

  roles:
    - { role: common, tags:['common']}

    # TODO - Change password of rabbit user - "edware"'s password
    # May need to rethink this, all rabbit servers are now using edware user
    # rabbitmqctl change_password edware {{ rabbit_user_password }}
    # See sensu-rabbit for a cleaner way
    - { role: rabbitmq, tags: ['rabbitmq', 'app'] }
    - { role: sensu, tags: ['sensu', 'monitoring'] }
