---
- name: Configure the standalone database postgres server 
  hosts: hpz-db:tsb-db:stats-db:migrate-db
  sudo: yes
  vars:
    monitoring_topics:
      - common 

  roles:
    - { role: common, tags:['common']}
    # TODO: We need to update postgres user names and password
    - { role: db, tags: ['db', 'app']}
    - { role: sensu, tags: ['sensu', 'monitoring'] }


