---
- name: Configure PgPool for PostreSQL connection pooling, load balancing, parallel queries 
  hosts: reporting-db-pgpool:extracts-db-pgpool
  user: ansible
  sudo: yes

  roles:
    - common
    - db-pgpool
