---

- name: Preflight variables
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Require spawner_env
      fail: 
        msg: "You must provide the 'spawner_env' variable via the -e option"
      when: spawner_env is not defined

- name: Provision GlusterFS storage
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    region: 'us-east-1' # TODO
  roles:
    - aws-creds
    - gluster-storage

- name: Install GlusterFS servers
  user: ansible
  sudo: yes
  hosts: gluster-server
  vars:
    node1: "{{ groups['gluster-server'] | intersect(groups[spawner_env])[0] }}"
    node2: "{{ groups['gluster-server'] | intersect(groups[spawner_env])[1] }}"
  roles:
    - common
    - gluster-server
