---
- name: Provision GlusterFS storage
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    region: 'us-east-1'
    aws_access_key: "{{ lookup('pipe', 'pass dev/aws/access_id') }}"
    aws_secret_key: "{{ lookup('pipe', 'pass dev/aws/secret_key') }}"
    node1: "{{ groups['gluster-server'] | intersect(groups[spawner_env])[0] }}"
    node2: "{{ groups['gluster-server'] | intersect(groups[spawner_env])[1] }}"
  roles:
    - gluster-storage

- name: Install GlusterFS servers
  user: ansible
  sudo: yes
  hosts: gluster-server
  vars:
    node1: "{{ groups['gluster-server'] | intersect(groups[spawner_env])[0] }}"
    node2: "{{ groups['gluster-server'] | intersect(groups[spawner_env])[1] }}"
  roles:
    - common
    - gluster-server
