---
- name: Provision GlusterFS storage
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    region: 'us-east-1' # TODO
    node1: "{{ groups['gluster-server'] | intersect(groups[spawner_env])[0] }}"
    node2: "{{ groups['gluster-server'] | intersect(groups[spawner_env])[1] }}"
  roles:
    - aws-creds
    - gluster-storage
  tags:
    - slow

- name: Install GlusterFS servers
  user: ansible
  sudo: yes
  hosts: gluster-server
  vars:
    node1: "{{ groups['gluster-server'] | intersect(groups[spawner_env])[0] }}"
    node2: "{{ groups['gluster-server'] | intersect(groups[spawner_env])[1] }}"
  roles:
    - common
    - aws-cli
    - gluster-server
