---
- name: Configure HPZ Web servers 
  hosts: hpz-web 
  sudo: yes
  vars:
    monitoring_topics:
      - common 

  roles:
    - { role: common, tags:['common']}
    - { role: gluster-client, tags: ['gluster-client'] }
    - { role: hpz-web, tags: ['hpz-web', 'app'] }
    - { role: sensu, tags: ['sensu', 'monitoring'] }
