---
- name: Configure HPZ Web servers 
  hosts: hpz-web 
  sudo: yes
  vars:
    monitoring_topics:
      - common
    ssl_key_name: localhost

  roles:
    - { role: common, tags:['common']}
    - { role: gluster-client, tags: ['gluster-client'] }
    - { role: web-server, tags: ['web-server', 'app'] }
    - { role: hpz-web, tags: ['hpz-web', 'app'] }
    - { role: sensu, tags: ['sensu', 'monitoring'] }
