---
- name: Configure lz server 
  hosts: lz 
  user: ansible
  sudo: yes
  vars:
    edware_rpm_name: edsftp
    monitoring_topics:
      - common 

  roles:
    - { role: common, tags: ['common']}
    - { role: edware, tags: ['edware', 'app'] }
    - { role: lz, tags: ['lz', 'app'] }
    - { role: sensu, tags: ['sensu', 'monitoring'] }
