---
- name: Configure the reporting PDF-making workers
  hosts: reporting-worker-pdf
  user: ansible
  sudo: yes
  vars:
    monitoring_topics:
      - common 

  roles:
    - { role: common, tags:['common']}
    - { role: edware, tags: ['edware', 'app'] }
    - { role: gluster-client, tags: ['gluster-client'] }
    - { role: reporting-worker-pdf, tags: ['reporting-worker-pdf', 'app']}
    - { role: sensu, tags: ['sensu', 'monitoring'] }
