- name: Reporting rabbit services
  hosts: all
  sudo: yes
  vars:
    rabbitmq_ssl_s3_bucket: "srl-{{ ec2_tag_environment }}-services-ssl"

  roles:
    - { role: common, tags:['common']}
    - { role: rabbitmq-from-base, tags: ['rabbitmq'] }
