---
- name: Configure the reporting CSV/Extract worker machines
  hosts: reporting-worker-extract
  user: ansible
  sudo: yes
  vars:
    monitoring_topics:
      - common 
      - data_item_glusterfs
      - data_raw_glusterfs

  roles:
    - { role: common, tags:['common']}
    - { role: edware, tags: ['edware', 'app'] }
    - { role: aws-cli, tags: ['aws-cli'] }
    - { role: gluster-client, tags: ['gluster-client'] }
    - { role: reporting-worker-extract, tags: ['reporting-worker-extract', 'app']}
    - { role: sensu, tags: ['sensu', 'monitoring'] }
