---
- name: Configure the reporting CSV/Extract worker machines
  hosts: reporting-worker-extract
  user: ansible
  sudo: yes

  roles:
    - common
    - edware
    - reporting-worker-extract
    - gluster-client
