---
- name: Configure the reporting CSV/Extract worker machines
  hosts: reporting-worker-extract
  sudo: yes

  vars:
    monitoring_topics:
      - common 

  roles:
    - { role: common, tags:['common']}
    - { role: edware, tags: ['edware', 'app'] }
    - { role: gluster-client, tags: ['gluster-client'] }
    - { role: reporting-worker-extract, tags: ['reporting-worker-extract', 'app']}
    - { role: sensu, tags: ['sensu', 'monitoring'] }
