---
- name: Configure the reporting CSV/Extract worker machines
  hosts: reporting-worker-extract
  user: ansible
  sudo: yes

  vars_files:
    - reporting-worker-extract.yml

  roles:
    - common
    - edware
    - reporting-worker-extract
