---
- name: Configure the reporting PDF-making workers
  hosts: reporting-worker-pdf
  user: ansible
  sudo: yes

  roles:
    - common
    - edware
    - { role: aws-cli, tags: ['aws-cli'] }
    - { role: gluster-client, tags: ['gluster-client'] }
    - reporting-worker-pdf

