---
- name: Configure reporting-cache-warmer servers 
  hosts: reporting-cache-warmer 
  sudo: yes
  vars:
    monitoring_topics:
      - common 

  vars:
    monitoring_topics:
      - common 

  roles:
    - { role: common, tags:['common']}
    - { role: edware, tags: ['edware', 'app'] }
    - { role: reporting-cache-warmer, tags:['reporting-cache-warmer', 'app']}
    - { role: sensu, tags: ['sensu', 'monitoring'] }
