---
- name: Configure reporting-generator-pdf servers 
  hosts: reporting-generator-pdf 
  user: ansible
  sudo: yes

  vars_files:
    - reporting-pdf-generator.yml

  roles:
    - common
    - edware
    - reporting-generator-pdf
