- name: Reporting rabbit extract
  hosts: reporting-rabbit-extract
  sudo: yes
  vars:
    rabbitmq_ssl_s3_bucket: "srl-{{ ec2_tag_environment }}-extract-ssl"
    the_username: "{{ reporting_rabbit_extract_username }}"
    the_password: "{{ reporting_rabbit_extract_password }}"
    vhost_name: edextract


  roles:
    - { role: common, tags: [ 'common'] }
    - { role: rabbitmq-from-base, tags: [ 'rabbitmq'] }
