- name: Upgrade RPMs for reporting-web
  hosts: reporting-web
  tags:
    - reporting-web
    - web
  vars:
    rpm_name: smarter
    service_name: httpd
  sudo: yes
  gather_facts: false
    
  tasks:
    - name: check existing version
      shell: "rpm -q {{ rpm_name }}"
      register: rpm_pre_check
      failed_when: false
      changed_when: false
      
    - name: "upgrade RPM"
      yum:
        name: "{{ rpm_name }}"
        state: latest
      notify: "restart {{ service_name }}"
      register: upgrade_result
      
    - name: check final version
      shell: "rpm -q {{ rpm_name }}"
      register: rpm_post_check
      changed_when: false
      
    - name: Log version change if any
      debug:
        msg: "RPM upgraded from {{ rpm_pre_check.stdout }} to {{ rpm_post_check.stdout }}"
      when: upgrade_result.changed
      
  handlers:
    - name: "restart {{ service_name }}"
      service:
        name: "{{ service_name }}"
        state: restarted

        
