- name: RMQ Server for Sensu
  hosts: sensu-rabbit
  sudo: yes
  vars:
    rabbitmq_ssl_s3_bucket: "srl-{{ ec2_tag_environment }}-sensu-ssl"
    monitoring_topics:
      - common 

  roles:
    - { role: common, tags: [ 'common'] }
    - { role: aws-cli, tags: [ 'aws-cli' ] }
    - { role: rabbitmq-from-base, tags: [ 'rabbitmq' ] }
    - { role: sensu-rabbit, tags: [ 'sensu-rabbit', 'app' ] }
    - { role: sensu, tags: ['sensu', 'monitoring'] }
