- name: Sensu Server (server, client, API, redis)
  hosts: sensu
  sudo: yes
  vars:
    ssl_key_name: graphite
    monitoring_topics:
      - common 
      - heartbeats
    sensu_install_server: true
    sensu_rubygems:
      - redphone

  vars_files:
    - roles/sensu/vars/check+metric-definitions.yml
    - roles/sensu/vars/handler-definitions.yml
    - roles/aws-creds/vars/main.yml

  roles:
    - { role: common, tags: ['common']}
    - { role: redis, tags: ['redis', 'app'] }
    - { role: carbon, tags: ['carbon', 'app'] }
    - { role: sensu, tags: ['sensu', 'app'] }
    - { role: web-server, tags: ['web-server', 'app'] }
