---
- name: Just say stuff
  hosts: localhost
  connection: local
  gather_facts: No
  
  tasks:

  - name: Show me the hosts
    debug: var=groups['gluster-server']

  - name: Show me the groups
    debug: var=group_names

  #- name: show me the hostvars
  #  debug: var=hostvars[{{ item }}]
  #  with_items: groups['gluster-server']

  #- name: Can I get more hostvars
  #  debug: var=hostvars['10.166.33.153']

  - name: Include the gluster storage variables
    include_vars: roles/gluster-storage/vars/gluster-storage.yml
    
  - name: Nested loop test
    debug: 
      msg: "For instance {{ hostvars[item[0]].ec2_id }} provision {{ item[1].dev }}"
    with_nested:
      - groups['gluster-server']
      - storage_devices

#  - name: Dump all variables
#    action: template src=dumpall.j2 dest=/tmp/ansible.all

