---
- name: Configure the tsb-worker servers 
  hosts: tsb-worker 
  sudo: yes
  vars:
    monitoring_topics:
      - common 

  vars:
    monitoring_topics:
      - common 

  roles:
    - { role: common, tags:['common']}
    - { role: edware, tags: ['edware', 'app'] }
    - { role: gluster-client, tags: ['gluster-client'] }
    - { role: tsb-worker, tags: ['tsb-worker', 'app'] }
    - { role: sensu, tags: ['sensu', 'monitoring'] }
