---
- name: Configure tsb-trigger server 
  hosts: tsb-trigger 
  sudo: yes
  vars:
    monitoring_topics:
      - common 

  roles:
    - { role: common, tags:['common']}
    - { role: gluster-client, tags: ['gluster-client'] }
    - { role: tsb-trigger, tags: ['tsb-trigger', 'app']}
    - { role: sensu, tags: ['sensu', 'monitoring'] }
