---
- name: Configure tsb-trigger server 
  hosts: tsb-trigger 
  user: ansible
  sudo: yes
  vars:
    edware_rpm_name: smarter_score_batcher
    monitoring_topics:
      - common 

  roles:
    - { role: common, tags: ['common']}
    - { role: edware, tags: ['edware', 'app'] }
    - { role: gluster-client, tags: ['gluster-client'] }
    - { role: tsb-trigger, tags: ['tsb-trigger', 'app']}
    - { role: sensu, tags: ['sensu', 'monitoring'] }
