- name: tsb-rabbit setup
  hosts: tsb-rabbit
  sudo: yes
  vars:
    monitoring_topics:
      - common 
      - rabbitmq 
    rabbitmq_ssl_s3_bucket: "srl-{{ ec2_tag_environment }}-tsb-ssl"
    rabbitmq_username: "{{ tsb_rabbit_username }}"
    rabbitmq_password: "{{ tsb_rabbit_password }}"
    sensu_rubygems:
      - carrot-top
    sensu_monitor_rabbitmq_queues: "smarter_score_batcher_sync, smarter_score_batcher_async, smarter_score_batcher_metadata"
    vhost_name: smarter_score_batcher

  roles:
    - { role: common, tags: [ 'common'] }
    - { role: aws-cli, tags: [ 'aws-cli' ] }
    - { role: rabbitmq-from-base, tags: [ 'rabbitmq' ] }
    - { role: sensu, tags: ['sensu', 'monitoring'] }
