- name: udl rabbitmq setup
  hosts: udl-rabbit
  sudo: yes
  vars:
    rabbitmq_ssl_s3_bucket: "srl-{{ ec2_tag_environment }}-udl-ssl"
    rabbitmq_username: "{{ udl_rabbit_username }}"
    rabbitmq_password: "{{ udl_rabbit_password }}"
    vhost_name: edudl

  roles:
    - { role: common, tags:['common']}
    - { role: rabbitmq-from-base, tags: ['rabbitmq'] }
