---
- name: Configure the standalone database postgres server 
  hosts: udl-db
  user: ansible
  sudo: yes
  vars:
    monitoring_topics:
      - common 
      - zones_glusterfs

  roles:
    - { role: common, tags: ['common']}
    - { role: gluster-client, tags: ['gluster-client'] }
    # TODO: We need to update postgres user names and password
    - { role: db, tags: ['db', 'app'] }
    - { role: sensu, tags: ['sensu', 'monitoring'] }
