- name: udl rabbitmq setup
  hosts: udl-rabbit
  sudo: yes
  vars:
    monitoring_topics:
      - common 
      - rabbitmq 
    rabbitmq_ssl_s3_bucket: "srl-{{ ec2_tag_environment }}-udl-ssl"
    rabbitmq_username: "{{ udl_rabbit_username }}"
    rabbitmq_password: "{{ udl_rabbit_password }}"
    sensu_rubygems:
      - carrot-top
    sensu_monitor_rabbitmq_queues: "udl2"
    vhost_name: udl

  roles:
    - { role: common, tags: ['common']}
    - { role: rabbitmq-from-base, tags: ['rabbitmq'] }
    - { role: sensu, tags: ['sensu', 'monitoring'] }
