---
- name: Configure the standalone database postgres server 
  hosts: udl-db
  user: ansible
  sudo: yes

  roles:
    - common
    - { role: aws-cli, tags: ['aws-cli'] }
    - { role: gluster-client, tags: ['gluster-client'] }
    - db
# We might need to update postgres user names and password
