---
- name: Configure the udl servers 
  hosts: udl 
  sudo: yes
  vars:
    monitoring_topics:
      - common 

  roles:
    - { role: common, tags:['common']}
    - { role: edware, tags: ['edware', 'app'] }
    - { role: gluster-client, tags: ['gluster-client'] }
    - { role: udl, tags: ['udl', 'app']}
    - { role: sensu, tags: ['sensu', 'monitoring'] }
