---
- name: Configure the udl servers 
  hosts: udl 
  user: ansible
  sudo: yes

  roles:
    - common
    - edware
    - { role: aws-cli, tags: ['aws-cli'] }
    - { role: gluster-client, tags: ['gluster-client'] }
    - udl 
