---
- name: Upgrade All
  hosts: all:!ansible
  sudo: yes
  tasks:

    - name: yum kernel upgrade
      yum:
        name: "kernel*"
        state: latest
      register: kernel_changed
    
    - name: yum full upgrade
      yum:
        name: "*"
        state: latest
        
    - name: Verify /etc/grub.conf file is a link
      file:
        src: /boot/grub/grub.conf
        dest: /etc/grub.conf
        state: link
        
    - name: fix grub.conf to use latest kernel
      lineinfile:
        dest: /boot/grub/grub.conf
        regexp: "^default="
        line: "default=0"
      when: "{{ kernel_changed | changed }}"
        
    - name: reboot
      command: shutdown -r now "Ansible reboot"
      async: 0
      poll: 0
      ignore_errors: true
      when: "{{ kernel_changed | changed }}"
      
    - name: wait for server to come back
      local_action: wait_for host={{ inventory_hostname }} state=started
      sudo: false
      when: "{{ kernel_changed | changed }}"
