---
- name: Upgrade All
  hosts: all:!ansible:!nat
  sudo: yes
  tasks:

    # ======================#
    # OS Packages upgrade
    # ======================#
    # TODO: address broken ordereddict package
    
    - name: yum full upgrade
      yum:
        name: "*"
        state: latest

    # ======================#
    # Kernel upgrade
    # ======================#
    
    - name: yum kernel upgrade
      yum:
        name: "kernel*"
        state: latest
    
    - name: Verify /etc/grub.conf file is a link
      file:
        src: /boot/grub/grub.conf
        dest: /etc/grub.conf
        state: link
        
    - name: fix grub.conf to use latest kernel
      lineinfile:
        dest: /boot/grub/grub.conf
        regexp: "^default="
        line: "default=0"
      register: grub_check # This will change if the kernel was upgraded
        
     - name: reboot
       command: shutdown -r now "Ansible reboot"
       async: 0
       poll: 0
       ignore_errors: true
       when: "{{ grub_check | changed }}"
      
     - name: wait for server to come back
       local_action: wait_for host={{ inventory_hostname }} state=started
       sudo: false
       when: "{{ grub_check | changed }}"
