- name: Wait for SSH
  hosts: all # Pass in -l to restrict
  connection: local
  sudo: no
  gather_facts: no
  tasks:
    - local_action: wait_for port=22 host="{{ inventory_hostname }}" search_regex=OpenSSH delay=2
