---

# Variables used to locate services.  

#-------------------------------------------------------------#
#                    External Services 
#             must be configured here by hand
#-------------------------------------------------------------#

pickup_host: lzsftpudl0.qa.dum.edwdc.net
sso_host: sso.sbac2.net # TODO: This does not resolve in Dev VPC bind or public DNS
extract_keyserver_host: rbtmqdw0.qa.dum.edwdc.net
file_grabber_lz_remote_host: lzsftpudl0.qa.dum.edwdc.net
file_grabber_tsb_remote_host: tsb.qa.dum.edwdc.net
# This setting makes no sense to me: not sure what app, and why is it a RMQ host?
sftp_remote_lz_host: rbtmqudl0.qa.dum.edwdc.net
pdf_base_url_host: ha-int-pyweb0.qa.dum.edwdc.net
tsb_rabbit_host: dwqldr0.qa.dum.edwdc.net
tsb_db_host: dbpgudl0.qa.dum.edwdc.net


#-------------------------------------------------------------#
#                   Internal Services
#            that could be dynamically looked up
#-------------------------------------------------------------#
bind_host: 10.166.32.10 # TODO: dynamic

#-------------------------------------------------------------#
#                   Internal Services
#                   set via local DNS
#-------------------------------------------------------------#
# These hostnames are machines in our VPC that have registered their names in BIND. 
# "should" be able to rely on local DNS without having to change these values.
# TODO: may be able to push these up to global_vars if we can parameterize the .dev. part
cache_host: srl-memcached.dev.ae1.sbac2dc.net
edware_db_ca_host: srl-db-pgpool.dev.ae1.sbac2dc.net # TODO: multi-tenancy
edware_repmgr_db_host : srl-db-master.dev.ae1.sbac2dc.net 
edware_stats_db_host: srl-db-util.dev.ae1.sbac2dc.net
hpz_web_host: srl-hpz-web.dev.ae1.sbac2dc.net
migrate_dest_db_ca_host: srl-db-master.dev.ae1.sbac2dc.net # TODO: multi-tenancy
migrate_rabbit_host: srl-rabbit.dev.ae1.sbac2dc.net
migrate_source_db_ca_host: srl-db-master.dev.ae1.sbac2dc.net # TODO: multi-tenancy
reporting_rabbit_host: srl-rabbit.dev.ae1.sbac2dc.net
reporting_rabbit_extract_host: srl-rabbit.dev.ae1.sbac2dc.net


