---
- name: Copy Logstash Repo
  copy: src=logstash.repo dest=/etc/yum.repos.d/logstash.repo

- name: Copy Elasticsearch Repo
  copy: src=elasticsearch.repo dest=/etc/yum.repos.d/elasticsearch.repo

- name: Logstash GPG
  copy: src=GPG-KEY-elasticsearch dest=/etc/pki/rpm-gpg

- name: Install Logstash
  yum: name=logstash state=present

- name: Install Elasticsearch 
  yum: name=elasticsearch state=present

#The default configuration is fine for ES
- name: Start Elasticsearch
  service: name=elasticsearch state=started enabled=yes

- name: Configure logstash
  template: src=logstash.conf dest=/etc/logstash/conf.d/
  notify: restart logstash  

- name: Start Logstash 
  service: name=logstash state=started enabled=yes
