---
- name: Install RPMs for webserver
  yum:
    name: "{{ item }}"
    state: present    
  with_items:
    - python3-3.3.0
    - httpd-2.2.15
    - python3-mod_wsgi-3.4
    - xmlsec1-1.2.20
    - xmlsec1-openssl-devel-1.2.20
  tags:
    - slow

- name: Set sysconfig to use worker MPM
  copy:
    src: etc-sysconfig-httpd
    dest: /etc/sysconfig/httpd    
  notify:
    - restart_httpd

