---

- name: Install version-pinned RPMs for webserver
  yum:
    name: "{{ item }}"
    state: present    
  with_items:
    - python3-3.3.0
    - httpd-2.2.15
    - python3-mod_wsgi-3.4
    - xmlsec1-1.2.20
    - xmlsec1-openssl-devel-1.2.20
  tags:
    - slow

- name: Install float-version RPMs for webserver
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - mod_ssl
  notify:
    - restart_httpd
  tags:
    - slow

- name: get appropriate SSL certs
  shell: '/usr/local/bin/aws s3 sync --sse s3://srl-{{ec2_tag_environment}}-apache-internal-ssl/reporting-web /etc/pki/tls/'
  register: rmq_s3_sync
  changed_when: "rmq_s3_sync.stdout != ''"
  notify:
    - restart_httpd
    
- name: Set sysconfig to use worker MPM
  copy:
    src: etc-sysconfig-httpd
    dest: /etc/sysconfig/httpd    
  notify:
    - restart_httpd

- name: Main httpd.conf
  template:
    src: httpd.conf.j2
    dest: /etc/httpd/conf/httpd.conf
  notify:
    - restart_httpd

- name: Remove default welcome.conf
  file:
    path: /etc/httpd/conf.d/welcome.conf
    state: absent
    
- name: Untemplated conf files
  copy:
    src: "{{ item }}"
    dest: "/etc/httpd/conf.d/{{ item }}"
  with_items:
    - security.conf      
  notify:
    - restart_httpd
    
