---
- name: stop PostgreSQL
  service: name=postgresql-9.2 state=stopped

- name: Install postgresql92-contrib
  yum: name=postgresql92-contrib state=latest

- name: start PostgreSQL
  service: name=postgresql-9.2 state=started
